<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />



<meta name="date" content="2023-12-04" />

<title>HIV/AIDS Surveillance Data Analysis across Countries</title>

<script src="site_libs/header-attrs-2.24/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/yeti.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.13.2/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<script src="site_libs/htmlwidgets-1.6.2/htmlwidgets.js"></script>
<script src="site_libs/viz-1.8.2/viz.js"></script>
<link href="site_libs/DiagrammeR-styles-0.2/styles.css" rel="stylesheet" />
<script src="site_libs/grViz-binding-1.0.10/grViz.js"></script>
<link href="site_libs/font-awesome-6.4.2/css/all.min.css" rel="stylesheet" />
<link href="site_libs/font-awesome-6.4.2/css/v4-shims.min.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>






<link rel="stylesheet" href="style.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Global HIV Hub</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="analysis_draft.html">HIV Surveillance</a>
</li>
<li>
  <a href="NHANES.html">Risk Factors</a>
</li>
<li>
  <a href="extra_resources.html">Resources</a>
</li>
<li>
  <a href="https://github.com/IamHJJ/p8105_final_project.github.io">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">HIV/AIDS Surveillance Data Analysis across
Countries</h1>
<h4 class="date">2023-12-04</h4>

</div>


<div id="about-data-source" class="section level1">
<h1>About Data Source</h1>
<p>The <a
href="https://www.census.gov/programs-surveys/international-programs/about/hiv.html">United
States Census HIV/AIDS Surveillance Data Base</a> contains information
for all countries and areas of the world with at least 5,000 population,
with the exception of Northern America (including the United States) and
U.S. territories. Data included in the Data Base are drawn from medical
and scientific journals, professional papers, official statistics, State
Department cables, newspapers, magazines, materials from the World
Health Organization, conference abstracts, and the Internet. Sources are
scanned and reviewed for data.</p>
</div>
<div id="study-objective" class="section level1">
<h1>Study Objective</h1>
<p>The primary objective of this study is to elucidate the temporal
dynamics and influential factors affecting HIV incidence rates on a
global scale, with a particular focus on diverse sub-populations and
geographic regions. We aim to achieve this by conducting a detailed
meta-analysis that includes time series and regression analyses to
identify significant trends, patterns, and associations. Specifically,
our analysis leverages ARIMA modeling to investigate time-dependent
trends and linear regression to assess the impact of socioeconomic
factors, thereby informing targeted public health strategies. The study
places a special emphasis on Sub-Saharan Africa, where preliminary
findings indicate a general decline in incidence rates among key
sub-populations, such as sex workers, since the early 1990s. By
dissecting these trends across varying income groups and regions, we
seek to prioritize interventions and allocate resources more effectively
in the global fight against HIV.</p>
</div>
<div id="data-cleaning-and-preparation" class="section level1">
<h1>Data Cleaning and Preparation</h1>
<pre class="r"><code>library(tidyverse) # for data cleaning
library(dplyr)     # for data cleaning
library(broom)     # for visualization
library(ggplot2)   # for visualization
library(forecast)  # for ARIMA models
library(ggplot2)   # for plotting
library(dplyr)     # for data manipulation
library(broom)     # for tidying model outputs</code></pre>
<p>Since the dataset has inconsistency in sample size (some come with a
sample size and some come without), we assigned the median value to
those without sample size so that they could be included in the study
without significantly influencing the <code>sample size</code> variable.
Since the Data Base includes data from all countries worldwide with
5000+ population, we utilized an external country classification dataset
from the <a
href="https://datahelpdesk.worldbank.org/knowledgebase/articles/906519-world-bank-country-and-lending-groups">World
Bank</a> to categorize the Data Base for analysis purposes.</p>
<pre class="r"><code>incidence &lt;- read.csv(&quot;surveillance/data/hiv_incidence.csv&quot;) |&gt;
  mutate(
    # Replace missing INC_RATE with 0 or other appropriate value
    INC_RATE = replace(INC_RATE, is.na(INC_RATE), 0), 
    # Replace missing SAMPSIZE with median or other appropriate value
    SAMPSIZE = replace(SAMPSIZE, is.na(SAMPSIZE), median(SAMPSIZE, na.rm = TRUE)) 
  )

country_info &lt;- readxl::read_excel(&quot;surveillance/CLASS.xlsx&quot;, sheet = &quot;List of economies&quot;, col_names = TRUE)

incidence_grouped &lt;- left_join(incidence, country_info, by = c(&quot;Country.Code&quot; = &quot;Code&quot;)) |&gt; 
  janitor::clean_names()

categorize_decade &lt;- function(year) {
  paste0(substr(year, 1, 3), &quot;0s&quot;)
}

incidence_grouped &lt;- incidence_grouped |&gt; 
  mutate(decade = sapply(year, categorize_decade)) </code></pre>
</div>
<div id="trend-analysis" class="section level1">
<h1>Trend Analysis</h1>
<p>We attempted to understand trends within the dataset through two
paths.</p>
<ul>
<li>First, we categorized data by their continental region, their
studied country’s national income level, and decade of which the study
is done. We produced a heatmap for reported HIV incidence rate grouped
by these categories.</li>
<li>Second, we categorized data by each study’s reported target
population (or population subgroup). We produced a barchart for reported
number of HIV cases grouped by these categories.</li>
</ul>
<pre class="r"><code># For trend analysis involving region (continental), income_group (i.e., high-income, low-income, middle-income countries), and decade (1980s, 1990s, 2000s, 2010s, 2020s).
trend_continental &lt;- incidence_grouped |&gt;
  # Convert &#39;no_cases&#39; to numeric (if it&#39;s not already)
  mutate(no_cases = as.numeric(no_cases)) |&gt;
  # -1 is a placeholder in the no_cases and no_deaths column for NA. Replace -1 with 0 here.
  mutate(no_cases = ifelse(no_cases == -1, 0, no_cases)) |&gt;
  # Group and summarize data by region, income_group, and decade
  group_by(region, income_group, decade) |&gt;
  summarize(
    avg_inc_rate = mean(inc_rate, na.rm = TRUE),
    total_cases = sum(no_cases, na.rm = TRUE),
    .groups = &#39;drop&#39;  # to drop grouping structure after summarization
  )

# For trend analysis involving population subgroup, e.g., MSM, IVDU, Transgender individuals, etc.
trend_subgroup &lt;- incidence_grouped |&gt;
  # Convert &#39;no_cases&#39; to numeric (if it&#39;s not already)
  mutate(no_cases = as.numeric(no_cases)) |&gt;
  # -1 is a placeholder in the no_cases and no_deaths column for NA. Replace -1 with 0 here.
  mutate(no_cases = ifelse(no_cases == -1, 0, no_cases)) |&gt;
  # Group and summarize data by population subgroup
  group_by(population_subgroup) |&gt;
  summarize(
    avg_inc_rate = mean(inc_rate, na.rm = TRUE),
    total_cases = sum(no_cases, na.rm = TRUE),
    .groups = &#39;drop&#39;  # to drop grouping structure after summarization
  )</code></pre>
<ol style="list-style-type: decimal">
<li><strong>Heatmap for Incidence Rate by Region, Decade, and National
Income Level</strong></li>
</ol>
<pre class="r"><code>trend_continental &lt;- trend_continental |&gt; 
  mutate(avg_inc_rate = as.numeric(avg_inc_rate)) 

heatmap_plot &lt;- trend_continental |&gt; 
  ggplot(aes(x = decade, y = region, fill = avg_inc_rate)) + 
  geom_tile(color = &quot;white&quot;) +  
  scale_fill_gradient(low = &quot;white&quot;, high = &quot;red&quot;) +  
  facet_wrap(~income_group) +  
  theme_minimal() + 
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),  
    axis.title = element_text(size = 12),  
    legend.title = element_text(size = 10)  
  ) +
  labs(
    title = &quot;Heatmap of HIV Incidence Rate by Region, Decade, and Income Level&quot;,
    x = &quot;Decade&quot;,
    y = &quot;Region&quot;,
    fill = &quot;Avg Inc Rate&quot;
  )

print(heatmap_plot)</code></pre>
<p><img src="analysis_draft_files/figure-html/Trend-visualization-heatmap-1.png" width="960" /></p>
<ol start="2" style="list-style-type: decimal">
<li><strong>Bar Plot for Total Cases by Population
Subgroup</strong></li>
</ol>
<pre class="r"><code>trend_subgroup |&gt; 
  ggplot(aes(y = population_subgroup, x = total_cases, fill = population_subgroup)) + 
  geom_bar(stat = &quot;identity&quot;) +
  theme_minimal() +
  labs(title = &quot;Total HIV Cases by Population Subgroup&quot;,
       y = &quot;Population Subgroup&quot;,
       x = &quot;Total Cases&quot;) +
  theme(axis.text.y = element_text(size = 5, angle = 0),
        legend.position = &quot;none&quot;)</code></pre>
<p><img src="analysis_draft_files/figure-html/Trend-visualization-bar-1.png" width="768" /></p>
</div>
<div id="meta-analysis" class="section level1">
<h1>Meta-Analysis</h1>
<div id="analysis-plan-flowchart" class="section level2">
<h2>Analysis Plan Flowchart</h2>
<div class="grViz html-widget html-fill-item-overflow-hidden html-fill-item" id="htmlwidget-5de6c3d082e3db7f4f68" style="width:672px;height:480px;"></div>
<script type="application/json" data-for="htmlwidget-5de6c3d082e3db7f4f68">{"x":{"diagram":"\ndigraph flowchart {\n  \n  # Define nodes\n  node [shape = box]\n  A [label = \"Data Preparation\"]\n  B [label = \"Time-Series Analysis\"]\n  C [label = \"Regression Analysis\"]\n  D [label = \"Subgroup Analysis\"]\n  E [label = \"Meta-Regression\"]\n  F [label = \"Sensitivity Analysis\"]\n  G [label = \"Model Diagnostics\"]\n  H [label = \"Reporting Results\"]\n  I [label = \"Visualization\"]\n\n  # Define edges\n  A -> B\n  A -> C\n  B -> D\n  C -> D\n  D -> E\n  D -> F\n  E -> G\n  F -> G\n  G -> H\n  H -> I\n}","config":{"engine":"dot","options":null}},"evals":[],"jsHooks":[]}</script>
</div>
<div id="data-preparation-for-meta-analysis" class="section level2">
<h2>Data Preparation for Meta-Analysis</h2>
<pre class="r"><code>sorted_data &lt;- incidence_grouped |&gt; 
  arrange(year) |&gt;
  # Convert &#39;no_cases&#39; to numeric (if it&#39;s not already)
  mutate(no_cases = as.numeric(no_cases)) |&gt;
  # -1 is a placeholder in the no_cases and no_deaths column for NA. Replace -1 with 0 here.
  mutate(no_cases = ifelse(no_cases == -1, 0, no_cases))

# Transform the dataset to have one observation per time point per subgroup
grouped_data &lt;- sorted_data |&gt; 
  group_by(year, region, income_group, population_subgroup) |&gt; 
  summarize(
    mean_inc_rate = mean(inc_rate, na.rm = TRUE),
    sum_no_cases = sum(no_cases, na.rm = TRUE),
    .groups = &#39;drop&#39;  # This ensures the resulting tibble is not grouped
  )</code></pre>
</div>
<div id="time-series-analysis" class="section level2">
<h2>Time-Series Analysis</h2>
<p>Time series analysis is appropriate for examining how data points
indexed in time order (like yearly HIV incidence rates) change over
time. It is suitable for analyzing trends, seasonal patterns, or
forecasting future values. Since we wanted to assess HIV incidence rates
by year, time series analysis is a good match.</p>
<pre class="r"><code>library(dplyr)
library(forecast)
library(tseries)
library(purrr)

# Create a list of unique combinations of region, income_group, and population_subgroup
unique_combinations &lt;- grouped_data |&gt;
  distinct(region, income_group, population_subgroup)

# Function to perform time series analysis on a subset of data
perform_time_series_analysis &lt;- function(subset_data) {
  if (length(subset_data$mean_inc_rate) &lt; 50) {
    warning(paste(&quot;Not enough data points to fit ARIMA model for&quot;, unique(subset_data$region), unique(subset_data$income_group), unique(subset_data$population_subgroup)))
    return(NULL)
  }
  
  ts_data &lt;- ts(subset_data$mean_inc_rate, start = min(subset_data$year), frequency = 1)
  
  # Check for stationarity
  adf_test &lt;- adf.test(ts_data, alternative = &quot;stationary&quot;)
  
  # Fit ARIMA model
  arima_model &lt;- auto.arima(ts_data)
  
  # Diagnostics
  diagnostics &lt;- list(
    checkresiduals(arima_model, plot = FALSE)
  )
  
  # Return the results
  return(list(arima_model = arima_model, adf_test = adf_test, diagnostics = diagnostics))
}

# Modify the threshold here
threshold &lt;- 20  # or another number that makes sense for your data

# List to store results
time_series_results &lt;- list()

# Loop over each unique combination
for(i in seq_len(nrow(unique_combinations))) {
  # Filter the data for the current combination
  current_data &lt;- grouped_data |&gt;
    filter(
      region == unique_combinations$region[i],
      income_group == unique_combinations$income_group[i],
      population_subgroup == unique_combinations$population_subgroup[i]
    )
  
  # Perform time series analysis if data points are above the threshold
  if (nrow(current_data) &gt;= threshold) {
    ts_data &lt;- ts(current_data$mean_inc_rate, start = min(current_data$year), frequency = 1)
    
    # Check for stationarity
    adf_test &lt;- adf.test(ts_data, alternative = &quot;stationary&quot;)
    
    # Fit ARIMA model
    arima_model &lt;- auto.arima(ts_data)
    
    # Diagnostics
    diagnostics &lt;- list(
      checkresiduals(arima_model, plot = FALSE)
    )
    
    # Store the result with a unique name
    time_series_results[[paste(unique_combinations$region[i], unique_combinations$income_group[i], unique_combinations$population_subgroup[i], sep = &quot;_&quot;)]] &lt;- list(arima_model = arima_model, adf_test = adf_test, diagnostics = diagnostics)
  } else {
    warning(paste(&quot;Not enough data points to fit ARIMA model for combination&quot;, i, &quot;:&quot;, unique_combinations$region[i], unique_combinations$income_group[i], unique_combinations$population_subgroup[i]))
  }
}</code></pre>
<pre><code>## 
##  Ljung-Box test
## 
## data:  Residuals from ARIMA(0,1,2) with drift
## Q* = 8.4892, df = 3, p-value = 0.03691
## 
## Model df: 2.   Total lags used: 5</code></pre>
<pre class="r"><code># Check how many models were successfully fitted
length(time_series_results)</code></pre>
<pre><code>## [1] 1</code></pre>
<pre class="r"><code># View results if any models were fitted
if (length(time_series_results) &gt; 0) {
  time_series_results
} </code></pre>
<pre><code>## $`Sub-Saharan Africa_Lower middle income_Sex workers`
## $`Sub-Saharan Africa_Lower middle income_Sex workers`$arima_model
## Series: ts_data 
## ARIMA(0,1,2) with drift 
## 
## Coefficients:
##           ma1     ma2    drift
##       -1.5900  0.9355  -1.0622
## s.e.   0.4624  0.5196   0.5354
## 
## sigma^2 = 70.67:  log likelihood = -89.56
## AIC=187.12   AICc=189.12   BIC=192
## 
## $`Sub-Saharan Africa_Lower middle income_Sex workers`$adf_test
## 
##  Augmented Dickey-Fuller Test
## 
## data:  ts_data
## Dickey-Fuller = -3.0323, Lag order = 2, p-value = 0.1791
## alternative hypothesis: stationary
## 
## 
## $`Sub-Saharan Africa_Lower middle income_Sex workers`$diagnostics
## $`Sub-Saharan Africa_Lower middle income_Sex workers`$diagnostics[[1]]
## 
##  Ljung-Box test
## 
## data:  Residuals from ARIMA(0,1,2) with drift
## Q* = 8.4892, df = 3, p-value = 0.03691</code></pre>
<div id="results" class="section level3">
<h3>Results</h3>
<p><strong>ARIMA Model:</strong></p>
<ul>
<li><strong>Model Type</strong>: ARIMA(0,1,2) with drift indicates that
the model is an ARIMA model with no autoregressive terms (p=0), one
differencing (d=1 to make the series stationary), and two moving average
terms (q=2).</li>
<li><strong>Coefficients</strong>:
<ul>
<li><code>ma1</code>: The first moving average coefficient is -1.5900,
with a standard error of 0.4624. This is a significant coefficient given
the magnitude compared to its standard error.</li>
<li><code>ma2</code>: The second moving average coefficient is 0.9355,
with a standard error of 0.5196. This coefficient is also
significant.</li>
<li><code>drift</code>: The coefficient for the drift term is -1.0622,
with a standard error of 0.5354. This suggests a downward trend in the
series.</li>
</ul></li>
<li><strong>Model Fit</strong>:
<ul>
<li><code>sigma^2</code>: The estimated variance of the residuals is
70.67.</li>
<li><code>log likelihood</code>: The log-likelihood of the model is
-89.56, which is used to calculate AIC and BIC.</li>
<li><code>AIC</code>, <code>AICc</code>, <code>BIC</code>: These are
information criteria used to compare models, with lower values generally
indicating a better fit. The AICc is an adjusted version of the AIC for
small sample sizes.</li>
</ul></li>
<li><strong>Augmented Dickey-Fuller Test</strong>:
<ul>
<li>This test checks for the presence of unit roots, which are a sign of
non-stationarity in the time series.</li>
<li>The Dickey-Fuller value is -3.0323 with a p-value of 0.1791. Since
the p-value is greater than the common significance level of 0.05, the
test does not reject the null hypothesis of a unit root being present,
suggesting that the time series may not be stationary despite the
differencing.</li>
</ul></li>
<li><strong>Ljung-Box Test</strong>:
<ul>
<li>This test is used to determine if there are significant
autocorrelations in the residuals at lag k. Ideally, we want the p-value
to be above 0.05 to conclude that there are no significant
autocorrelations.</li>
<li>The test statistic is Q* = 8.4892 with a p-value of 0.03691. Since
the p-value is less than 0.05, this suggests that there is evidence of
significant autocorrelation at lag k within the residuals, which means
the model may not be adequately capturing all the patterns in the
data.</li>
</ul></li>
</ul>
</div>
<div id="interpretations-of-results" class="section level3">
<h3>Interpretations of results</h3>
<ul>
<li>The ARIMA model suggests a decreasing trend in the incidence rates
for the subgroup.</li>
<li>The ADF test suggests that the series may not be completely
stationary, indicating that further differencing or a different model
specification may be necessary.</li>
<li>The significant Ljung-Box test implies that there are
autocorrelations in the residuals that the model is not capturing, which
could mean that important predictors or higher-order lags might be
missing from the model. Given the limited information on the Data Base
we are using, we are unable to progress further. However, future
research may consider incorporating other predictors for the model.</li>
</ul>
</div>
<div id="time-series-trend-visualization" class="section level3">
<h3>Time Series Trend Visualization</h3>
<div id="select-which-modelcombination-to-visualize"
class="section level4">
<h4>1. Select which model/combination to visualize</h4>
<pre class="r"><code># Loop through the results and print the summary of each ARIMA model
for (combination in names(time_series_results)) {
  cat(&quot;\nCombination:&quot;, combination, &quot;\n&quot;)
  print(summary(time_series_results[[combination]]$arima_model))
}</code></pre>
<pre><code>## 
## Combination: Sub-Saharan Africa_Lower middle income_Sex workers 
## Series: ts_data 
## ARIMA(0,1,2) with drift 
## 
## Coefficients:
##           ma1     ma2    drift
##       -1.5900  0.9355  -1.0622
## s.e.   0.4624  0.5196   0.5354
## 
## sigma^2 = 70.67:  log likelihood = -89.56
## AIC=187.12   AICc=189.12   BIC=192
## 
## Training set error measures:
##                      ME     RMSE      MAE      MPE    MAPE      MASE      ACF1
## Training set -0.6193829 7.732668 5.426826 1.645182 139.093 0.7643619 0.4777973</code></pre>
<p>Based on the summary of the ARIMA model for the combination
“Sub-Saharan Africa_Lower middle income_Sex workers,” it looks like an
interesting case to visualize. The ARIMA(0,1,2) model with drift
indicates that the time series is differenced once (to make it
stationary) and includes two moving average terms. The drift term
suggests a linear trend over time.</p>
</div>
<div id="time-series-trend-visualization-1" class="section level4">
<h4>2. Time Series Trend Visualization</h4>
<pre class="r"><code># Extracting the data and model for &quot;Sub-Saharan Africa_Lower middle income_Sex workers&quot;
selected_model &lt;- time_series_results[[&quot;Sub-Saharan Africa_Lower middle income_Sex workers&quot;]]$arima_model
selected_data &lt;- grouped_data %&gt;%
  filter(
    region == &quot;Sub-Saharan Africa&quot;,
    income_group == &quot;Lower middle income&quot;,
    population_subgroup == &quot;Sex workers&quot;
  )
# Plotting the actual time series data and the fitted model
ggplot(selected_data, aes(x = year, y = mean_inc_rate)) +
  geom_line() +
  geom_line(aes(y = fitted(selected_model)), color = &quot;red&quot;) +
  labs(title = &quot;Time Series Trend and ARIMA Model for Sub-Saharan Africa, Lower Middle Income, Sex Workers&quot;,
       x = &quot;Year&quot;,
       y = &quot;Mean Incidence Rate&quot;) +
  theme_minimal()</code></pre>
<p><img src="analysis_draft_files/figure-html/time%20series%20visualize%20-%20visualization-1.png" width="672" /></p>
<ul>
<li><p>Black Line (Actual Data): Represents the actual observed values
of the mean incidence rate over time. This line shows the fluctuations
in the data across years.</p></li>
<li><p>Red Line (Fitted ARIMA Model): Represents the values as fitted by
the ARIMA model. The red line seems to follow the general downward trend
of the actual data, indicating that the model is capturing the overall
trend well.</p></li>
<li><p><strong>Interpretation of Trend</strong>: There is a notable
decrease in the mean incidence rate from the early 1990s, which then
stabilizes into a more fluctuating pattern from the 2000s onwards. The
red line (fitted values) is capturing this trend, suggesting that the
ARIMA model is accounting for the major trend in the data.</p></li>
</ul>
</div>
<div id="diagnostic-plots-for-the-arima-model" class="section level4">
<h4>3. Diagnostic Plots for the ARIMA Model</h4>
<pre class="r"><code># Diagnostic plots for the ARIMA model of the selected combination
checkresiduals(selected_model)</code></pre>
<p><img src="analysis_draft_files/figure-html/time%20series%20visualize%20-%20model%20diagnostic%20plot-1.png" width="672" /></p>
<pre><code>## 
##  Ljung-Box test
## 
## data:  Residuals from ARIMA(0,1,2) with drift
## Q* = 8.4892, df = 3, p-value = 0.03691
## 
## Model df: 2.   Total lags used: 5</code></pre>
<ul>
<li><p><strong>Top Plot (Residuals vs. Time)</strong>: This plot shows
the residuals of the model over time. Ideally, the residuals should be
randomly scattered around zero, indicating that the model has captured
most of the trend and seasonality. In your graph, residuals do not show
any clear pattern over time, which is good, but there seem to be certain
years with higher deviations from zero, which could indicate model
misspecification or the presence of outliers/anomalies.</p></li>
<li><p><strong>Bottom Left Plot (ACF of Residuals)</strong>: This plot
shows the autocorrelations of the residuals at different lags. Ideally,
we want to see these autocorrelations fall within the blue dashed lines,
which represent the confidence intervals. If they are within the blue
lines, it suggests that there is no significant autocorrelation in the
residuals, and the model has captured the time series’ structure well.
Our plot shows some autocorrelations at different lags crossing the
confidence bounds, which might suggest that the model could be improved
to better capture the time series dynamics.</p></li>
<li><p><strong>Bottom Right Plot (Histogram and Q-Q Plot of
Residuals)</strong>: The histogram with the overlaid density plot and
the Q-Q plot assess the normality of the residuals. The histogram seems
to show that residuals may be normally distributed, but the Q-Q plot
indicates some deviations from normality, particularly in the tails.
This suggests that the residuals have some heavier tails than the normal
distribution, which can occur if there are outliers or extreme values in
our data.</p></li>
</ul>
</div>
</div>
</div>
<div id="linear-regression-analysis" class="section level2">
<h2>Linear Regression Analysis</h2>
<p>Regression analysis is used to understand the relationship between a
dependent variable and one or more independent variables. It is suitable
for questions like how various factors (like region, income level,
population subgroup) are associated with the outcome (e.g., HIV
incidence rate). However, it should be noted that linear regression has
multiple assumptions as all other regressions, and on top of these,
linear regression assums normal distribution of the residuals.</p>
<pre class="r"><code>library(dplyr)
library(broom)

# Create a list of unique combinations of region and income_group
combinations_region_income &lt;- grouped_data |&gt;
  distinct(region, income_group)

# Create a list of unique population_subgroup
combinations_subpopulation &lt;- grouped_data |&gt;
  distinct(population_subgroup)

# Function to perform regression analysis on a subset of data
perform_regression_analysis &lt;- function(subset_data) {
  if (nrow(subset_data) &lt; 10) {  # Setting a threshold for the minimum number of data points
    warning(&quot;Not enough data points to fit regression model for the given combination.&quot;)
    return(NULL)
  }
  
  # Fit linear regression model
  reg_model &lt;- lm(mean_inc_rate ~ year, data = subset_data)
  
  # Collect the summary statistics of the model
  reg_summary &lt;- summary(reg_model)
  
  # Collect tidy results of the model for easy handling
  tidy_results &lt;- tidy(reg_model)
  
  # Return the results
  return(list(reg_model = reg_model, reg_summary = reg_summary, tidy_results = tidy_results))
}

# List to store results for region and income_group
regression_region_income_results &lt;- list()

# Loop over each region &amp; income level combination
for(i in seq_len(nrow(combinations_region_income))) {
  # Filter the data for the current combination
  current_data &lt;- grouped_data |&gt;
    filter(
      region == combinations_region_income$region[i],
      income_group == combinations_region_income$income_group[i]
    )
  
  # Perform regression analysis
  result &lt;- perform_regression_analysis(current_data)
  
  # Store the result with a unique name if result is not NULL
  if (!is.null(result)) {
    regression_region_income_results[[paste(combinations_region_income$region[i], combinations_region_income$income_group[i], sep = &quot;_&quot;)]] &lt;- result
  }
}

# List to store results for population_subgroup
regression_subpopulation_results &lt;- list()

# Loop over each population_subgroup
for(i in seq_len(nrow(combinations_subpopulation))) {
  # Filter the data for the current population_subgroup
  current_data &lt;- grouped_data |&gt;
    filter(
      population_subgroup == combinations_subpopulation$population_subgroup[i]
    )
  
  # Perform regression analysis
  result &lt;- perform_regression_analysis(current_data)
  
  # Store the result with a unique name if result is not NULL
  if (!is.null(result)) {
    regression_subpopulation_results[[combinations_subpopulation$population_subgroup[i]]] &lt;- result
  }
}

# Check the first element of regression_region_income_results to make sure it contains a valid model
if(length(regression_region_income_results) &gt; 0) {
  print(regression_region_income_results[[1]])
}</code></pre>
<pre><code>## $reg_model
## 
## Call:
## lm(formula = mean_inc_rate ~ year, data = subset_data)
## 
## Coefficients:
## (Intercept)         year  
##    0.230660     0.001763  
## 
## 
## $reg_summary
## 
## Call:
## lm(formula = mean_inc_rate ~ year, data = subset_data)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -3.7835 -3.3772 -0.2461  1.2854 10.3973 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) 2.307e-01  2.219e+02   0.001    0.999
## year        1.763e-03  1.103e-01   0.016    0.987
## 
## Residual standard error: 4.144 on 16 degrees of freedom
## Multiple R-squared:  1.596e-05,  Adjusted R-squared:  -0.06248 
## F-statistic: 0.0002554 on 1 and 16 DF,  p-value: 0.9874
## 
## 
## $tidy_results
## # A tibble: 2 × 5
##   term        estimate std.error statistic p.value
##   &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;
## 1 (Intercept)  0.231     222.      0.00104   0.999
## 2 year         0.00176     0.110   0.0160    0.987</code></pre>
<pre class="r"><code># Check the first element of regression_subpopulation_results to make sure it contains a valid model
if(length(regression_subpopulation_results) &gt; 0) {
  print(regression_subpopulation_results[[1]])
}</code></pre>
<pre><code>## $reg_model
## 
## Call:
## lm(formula = mean_inc_rate ~ year, data = subset_data)
## 
## Coefficients:
## (Intercept)         year  
##    57.78495     -0.02773  
## 
## 
## $reg_summary
## 
## Call:
## lm(formula = mean_inc_rate ~ year, data = subset_data)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -2.436 -1.851 -1.070  1.956  4.906 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept)  57.78495  106.35869   0.543    0.591
## year         -0.02773    0.05298  -0.523    0.605
## 
## Residual standard error: 2.165 on 29 degrees of freedom
## Multiple R-squared:  0.009357,   Adjusted R-squared:  -0.0248 
## F-statistic: 0.2739 on 1 and 29 DF,  p-value: 0.6047
## 
## 
## $tidy_results
## # A tibble: 2 × 5
##   term        estimate std.error statistic p.value
##   &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;
## 1 (Intercept)  57.8     106.         0.543   0.591
## 2 year         -0.0277    0.0530    -0.523   0.605</code></pre>
<div id="regression-model-diagnostics" class="section level3">
<h3>Regression Model Diagnostics</h3>
<p>Based on the results, we performed the following model
diagnostics:</p>
<ul>
<li><strong>Check for Linearity</strong>: Ensure that the relationship
between the predictor (year) and the response variable (mean_inc_rate)
is linear.</li>
<li><strong>Investigate Outliers</strong>: Large residuals may indicate
outliers, which can unduly influence the regression model. It might be
worth investigating these data points to see if they should be included
in the analysis.</li>
<li><strong>Consider Model Complexity</strong>: The model may be too
simple. Perhaps the relationship between year and incidence rate is not
linear, or there may be other variables or transformations that could
improve the model.</li>
</ul>
<pre class="r"><code># Function to plot diagnostics for a regression model
plot_regression_diagnostics &lt;- function(reg_model) {
  par(mfrow = c(2, 2))
  plot(reg_model)
}

# Perform diagnostics on the first element of regression_region_income_results
if(length(regression_region_income_results) &gt; 0) {
  plot_regression_diagnostics(regression_region_income_results[[1]]$reg_model)
}</code></pre>
<p><img src="analysis_draft_files/figure-html/linear-Model%20Diagnostics-1.png" width="672" /></p>
<pre class="r"><code># Perform diagnostics on the first element of regression_subpopulation_results
if(length(regression_subpopulation_results) &gt; 0) {
  plot_regression_diagnostics(regression_subpopulation_results[[1]]$reg_model)
}</code></pre>
<p><img src="analysis_draft_files/figure-html/linear-Model%20Diagnostics-2.png" width="672" /></p>
<p>For both sets of plots, the Residuals vs Fitted and Scale-Location
plots look acceptable, though there is some indication of potential
heteroscedasticity in the second set. The Q-Q Plots suggest that the
residuals may not be perfectly normally distributed, especially for the
second model. The Residuals vs Leverage plots indicate that there are
some influential points in the first model, particularly observation 70.
All of these <strong>warrants us to be careful in terms of our final
interpretation/conclusion</strong>.</p>
</div>
<div id="results-1" class="section level3">
<h3>Results</h3>
<ul>
<li><strong>Model Coefficients</strong>: The estimated coefficients for
the year variable in both models are quite small, indicating that time
may not have a strong influence on the mean_inc_rate for these
particular subsets of data.</li>
<li><strong>Statistical Significance</strong>: The p-values associated
with the year coefficient are very high (0.987 for the region-income
model and 0.605 for the subpopulation model), which means that the year
variable is not statistically significant in predicting the
mean_inc_rate in these models.</li>
<li><strong>Model Fit</strong>: The R-squared values are very close to
zero, which suggests that the models explain none of the variability in
the response data around its mean.</li>
<li><strong>Residuals</strong>: The residuals’ summary shows that there
might be some large residuals in the data, which could be potential
outliers or indicate model misspecification.</li>
</ul>
</div>
<div id="sensitivity-analysis" class="section level3">
<h3>Sensitivity Analysis</h3>
<p>Sensitivity analysis in the context of regression analysis is used to
determine how sensitive your results are to changes in the model. This
involves testing how the model’s predictions vary with changes in the
modeling approach, such as using different subsets of data, handling
outliers, or changing the model specification.</p>
<div id="varying-model-specification" class="section level4">
<h4>1. Varying Model Specification</h4>
<pre class="r"><code># Original model
original_model &lt;- lm(mean_inc_rate ~ year + region + income_group, data = grouped_data)

# Model excluding a potentially influential variable
model_without_variable &lt;- lm(mean_inc_rate ~ year + region, data = grouped_data)

# Compare the results
summary(original_model)</code></pre>
<pre><code>## 
## Call:
## lm(formula = mean_inc_rate ~ year + region + income_group, data = grouped_data)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -9.915 -3.420 -1.538  1.574 49.944 
## 
## Coefficients:
##                                   Estimate Std. Error t value Pr(&gt;|t|)   
## (Intercept)                      127.41820   62.21955   2.048  0.04094 * 
## year                              -0.06142    0.03099  -1.982  0.04783 * 
## regionEurope &amp; Central Asia        5.17868    1.72935   2.995  0.00284 **
## regionLatin America &amp; Caribbean   -0.63691    0.77852  -0.818  0.41357   
## regionMiddle East &amp; North Africa  -2.46132    1.66594  -1.477  0.14000   
## regionSouth Asia                   1.18550    1.40394   0.844  0.39873   
## regionSub-Saharan Africa           1.05570    0.68748   1.536  0.12508   
## income_groupLow income            -1.41851    1.32838  -1.068  0.28595   
## income_groupLower middle income    0.50643    1.24616   0.406  0.68458   
## income_groupUpper middle income    0.11720    1.09376   0.107  0.91470   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 5.841 on 708 degrees of freedom
## Multiple R-squared:  0.03775,    Adjusted R-squared:  0.02552 
## F-statistic: 3.086 on 9 and 708 DF,  p-value: 0.001211</code></pre>
<pre class="r"><code>summary(model_without_variable)</code></pre>
<pre><code>## 
## Call:
## lm(formula = mean_inc_rate ~ year + region, data = grouped_data)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -9.733 -3.491 -1.546  1.413 50.530 
## 
## Coefficients:
##                                  Estimate Std. Error t value Pr(&gt;|t|)   
## (Intercept)                      97.36613   60.70513   1.604  0.10918   
## year                             -0.04641    0.03019  -1.537  0.12473   
## regionEurope &amp; Central Asia       5.16548    1.73263   2.981  0.00297 **
## regionLatin America &amp; Caribbean  -0.62219    0.77997  -0.798  0.42531   
## regionMiddle East &amp; North Africa -2.23179    1.56566  -1.425  0.15446   
## regionSouth Asia                  1.53599    1.25906   1.220  0.22289   
## regionSub-Saharan Africa          0.71239    0.49622   1.436  0.15155   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 5.861 on 711 degrees of freedom
## Multiple R-squared:  0.02728,    Adjusted R-squared:  0.01907 
## F-statistic: 3.323 on 6 and 711 DF,  p-value: 0.003106</code></pre>
<p><strong>Original Model vs. Model Without
<code>income_group</code>:</strong></p>
<ul>
<li>The presence or absence of income_group as a predictor does not seem
to drastically change the R-squared value, indicating that while
income_group contributes some information, it might not be a major
driver in the model.</li>
<li>The coefficients of year and region remain relatively stable between
the two models, suggesting that their influence is somewhat independent
of income_group.</li>
<li>The significance levels (Pr(&gt;|t|)) for most variables remained
similar, indicating that the overall statistical relationships in your
model are robust to the inclusion/exclusion of income_group.</li>
</ul>
</div>
<div id="handling-outliers" class="section level4">
<h4>2. Handling Outliers</h4>
<pre class="r"><code># Identify outliers (example using Cook&#39;s distance)
cooksd &lt;- cooks.distance(original_model)
outlier_threshold &lt;- 4 / length(cooksd)
outliers &lt;- which(cooksd &gt; outlier_threshold)

# Model without outliers
model_without_outliers &lt;- lm(mean_inc_rate ~ year + region + income_group, data = grouped_data[-outliers,])

# Compare the results
summary(original_model)</code></pre>
<pre><code>## 
## Call:
## lm(formula = mean_inc_rate ~ year + region + income_group, data = grouped_data)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -9.915 -3.420 -1.538  1.574 49.944 
## 
## Coefficients:
##                                   Estimate Std. Error t value Pr(&gt;|t|)   
## (Intercept)                      127.41820   62.21955   2.048  0.04094 * 
## year                              -0.06142    0.03099  -1.982  0.04783 * 
## regionEurope &amp; Central Asia        5.17868    1.72935   2.995  0.00284 **
## regionLatin America &amp; Caribbean   -0.63691    0.77852  -0.818  0.41357   
## regionMiddle East &amp; North Africa  -2.46132    1.66594  -1.477  0.14000   
## regionSouth Asia                   1.18550    1.40394   0.844  0.39873   
## regionSub-Saharan Africa           1.05570    0.68748   1.536  0.12508   
## income_groupLow income            -1.41851    1.32838  -1.068  0.28595   
## income_groupLower middle income    0.50643    1.24616   0.406  0.68458   
## income_groupUpper middle income    0.11720    1.09376   0.107  0.91470   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 5.841 on 708 degrees of freedom
## Multiple R-squared:  0.03775,    Adjusted R-squared:  0.02552 
## F-statistic: 3.086 on 9 and 708 DF,  p-value: 0.001211</code></pre>
<pre class="r"><code>summary(model_without_outliers)</code></pre>
<pre><code>## 
## Call:
## lm(formula = mean_inc_rate ~ year + region + income_group, data = grouped_data[-outliers, 
##     ])
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -4.5939 -2.6421 -0.9381  1.7817 13.7103 
## 
## Coefficients:
##                                  Estimate Std. Error t value Pr(&gt;|t|)   
## (Intercept)                      49.66804   38.26486   1.298  0.19473   
## year                             -0.02355    0.01905  -1.236  0.21675   
## regionEurope &amp; Central Asia       4.19776    1.97847   2.122  0.03423 * 
## regionLatin America &amp; Caribbean  -0.16126    0.46045  -0.350  0.72629   
## regionMiddle East &amp; North Africa -3.03315    1.01515  -2.988  0.00291 **
## regionSouth Asia                 -0.02764    0.87981  -0.031  0.97494   
## regionSub-Saharan Africa          0.62400    0.40962   1.523  0.12814   
## income_groupLow income            0.10593    0.82565   0.128  0.89796   
## income_groupLower middle income   1.37865    0.77953   1.769  0.07742 . 
## income_groupUpper middle income   1.12057    0.68721   1.631  0.10344   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 3.403 on 671 degrees of freedom
## Multiple R-squared:  0.04719,    Adjusted R-squared:  0.03441 
## F-statistic: 3.692 on 9 and 671 DF,  p-value: 0.0001565</code></pre>
<p><strong>Original Model vs. Model Without Outliers:</strong></p>
<ul>
<li>Removing outliers leads to a noticeable change in the coefficients
and their standard errors, suggesting that outliers had some influence
on the model estimates.</li>
<li>The R-squared value improves slightly in the model without outliers,
which could indicate a better fit.</li>
<li>The residual standard error decreases significantly when outliers
are removed, suggesting that these outliers were contributing to a
larger error in the original model.</li>
</ul>
</div>
<div id="using-different-data-subsets" class="section level4">
<h4>3. Using Different Data Subsets</h4>
<pre class="r"><code># Splitting the data into two subsets
set.seed(123)  # for reproducibility
data_subset1 &lt;- grouped_data[sample(nrow(grouped_data), nrow(grouped_data) / 2), ]
data_subset2 &lt;- grouped_data[!rownames(grouped_data) %in% rownames(data_subset1), ]

# Fit the model to each subset
model_subset1 &lt;- lm(mean_inc_rate ~ year + region + income_group, data = data_subset1)
model_subset2 &lt;- lm(mean_inc_rate ~ year + region + income_group, data = data_subset2)

# Compare the results
summary(model_subset1)</code></pre>
<pre><code>## 
## Call:
## lm(formula = mean_inc_rate ~ year + region + income_group, data = data_subset1)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -7.208 -3.174 -1.463  1.681 35.677 
## 
## Coefficients:
##                                   Estimate Std. Error t value Pr(&gt;|t|)  
## (Intercept)                      121.27485   82.14200   1.476    0.141  
## year                              -0.05851    0.04087  -1.431    0.153  
## regionEurope &amp; Central Asia        2.24783    2.40264   0.936    0.350  
## regionLatin America &amp; Caribbean   -1.59627    0.93883  -1.700    0.090 .
## regionMiddle East &amp; North Africa  -3.09265    2.22111  -1.392    0.165  
## regionSouth Asia                  -0.11015    2.07443  -0.053    0.958  
## regionSub-Saharan Africa           1.41334    0.87997   1.606    0.109  
## income_groupLow income            -1.97526    1.79582  -1.100    0.272  
## income_groupLower middle income    0.41310    1.71055   0.242    0.809  
## income_groupUpper middle income    0.65587    1.47201   0.446    0.656  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 5.166 on 349 degrees of freedom
## Multiple R-squared:  0.04917,    Adjusted R-squared:  0.02465 
## F-statistic: 2.005 on 9 and 349 DF,  p-value: 0.03793</code></pre>
<pre class="r"><code>summary(model_subset2)</code></pre>
<pre><code>## 
## Call:
## lm(formula = mean_inc_rate ~ year + region + income_group, data = data_subset2)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -10.892  -3.212  -1.157   1.350  48.761 
## 
## Coefficients:
##                                    Estimate Std. Error t value Pr(&gt;|t|)   
## (Intercept)                      -390.27351  192.70970  -2.025  0.04361 * 
## year                                0.19479    0.09565   2.036  0.04247 * 
## regionEurope &amp; Central Asia         6.41219    2.23264   2.872  0.00433 **
## regionLatin America &amp; Caribbean     0.42624    1.13003   0.377  0.70626   
## regionMiddle East &amp; North Africa   -3.87273    1.75045  -2.212  0.02758 * 
## regionSouth Asia                    0.67433    1.99230   0.338  0.73521   
## regionSub-Saharan Africa            1.63880    0.80680   2.031  0.04299 * 
## income_groupLow income              0.98936    1.94090   0.510  0.61056   
## income_groupLower middle income     1.51186    1.79845   0.841  0.40112   
## income_groupUpper middle income     1.41738    1.61209   0.879  0.37989   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 5.35 on 349 degrees of freedom
## Multiple R-squared:  0.07208,    Adjusted R-squared:  0.04815 
## F-statistic: 3.012 on 9 and 349 DF,  p-value: 0.001779</code></pre>
<p><strong>Model on Subset 1 vs. Model on Subset 2:</strong></p>
<ul>
<li>There are some differences in the coefficients and their
significance between the two subsets, indicating potential variability
in the data or the influence of specific predictors.</li>
<li>The R-squared values differ between the subsets, which could
indicate variability in how well the model explains the variance in the
dependent variable across different samples of the data.</li>
</ul>
</div>
<div id="bootstrap-resampling" class="section level4">
<h4>4. Bootstrap Resampling</h4>
<pre class="r"><code># Bootstrap resampling
library(boot)

# Function to obtain coefficients
boot_function &lt;- function(data, indices) {
  sample_data &lt;- data[indices, ]
  model &lt;- lm(mean_inc_rate ~ year + region + income_group, data = sample_data)
  return(coef(model))
}

# Running bootstrap
bootstrap_results &lt;- boot(grouped_data, boot_function, R = 1000)

# View summary of bootstrap results
boot.ci(bootstrap_results, type = &quot;bca&quot;)</code></pre>
<pre><code>## BOOTSTRAP CONFIDENCE INTERVAL CALCULATIONS
## Based on 1000 bootstrap replicates
## 
## CALL : 
## boot.ci(boot.out = bootstrap_results, type = &quot;bca&quot;)
## 
## Intervals : 
## Level       BCa          
## 95%   (-46.1, 296.6 )  
## Calculations and Intervals on Original Scale</code></pre>
<p><strong>Bootstrap Confidence Intervals:</strong></p>
<ul>
<li>The BCa interval you provided appears to be wide ((-46.1, 296.6)),
suggesting a considerable amount of uncertainty in the estimate.
However, without knowing which coefficient this interval corresponds to,
it’s challenging to draw specific conclusions.</li>
<li>Wide confidence intervals in bootstrap results suggest variability
in your model’s estimates and a need for caution in interpreting the
model’s predictive power.</li>
</ul>
</div>
<div id="interpreting-sensitivity-analysis" class="section level4">
<h4>5. Interpreting Sensitivity Analysis</h4>
<p><strong>General Observations</strong></p>
<ul>
<li>Our model shows some sensitivity to the inclusion of certain
predictors and the presence of outliers. This suggests the need for
careful consideration of model specifications and data quality.</li>
<li>The differences in model outcomes between data subsets imply that
the relationships in our data is entirely consistent across different
samples. This could be due to underlying variability in the data or
different patterns within subgroups of the data.</li>
</ul>
<p><strong>Recommendations for Future Research</strong></p>
<ul>
<li>Consider whether any additional variables, not included in the
model, might explain some of the variability and improve the model’s
consistency.</li>
<li>Explore if different modeling approaches, such as segmented
regression or hierarchical models, might better account for the
variability in the data.</li>
</ul>
</div>
</div>
</div>
</div>
<div id="conclusion" class="section level1">
<h1>Conclusion</h1>
<p>The study has identified meaningful patterns in the incidence rates
of HIV among various subgroups in Sub-Saharan Africa. The time series
analysis, particularly the ARIMA(0,1,2) model with drift, has captured a
notable decreasing trend in HIV incidence rates since the early 1990s.
This trend stabilizes somewhat in the 2000s, with some fluctuation, but
does not show a significant increase, indicating a potential
effectiveness of interventions and awareness over time. Diagnostic plots
suggest that while the model fits well overall, there are indications of
outliers or anomalous events that could be affecting the residuals,
pointing to areas where the model could be refined.</p>
<p>The linear regression analysis further enhances our understanding by
evaluating the impact of various factors such as year, region, and
income group on HIV incidence rates. Sensitivity analysis indicates that
the model’s findings are relatively robust, although some sensitivity to
model specifications and outliers was noted. This suggests that while
the model provides a solid baseline understanding, it could benefit from
further refinement.</p>
<p>The overall conclusion is that HIV incidence rates in Sub-Saharan
Africa show a decreasing trend over the years among sex workers, with
some variability that might be explained by regional and economic
factors. The analysis underscores the importance of tailored public
health interventions and the need for continuous monitoring and
adaptation to sustain and enhance the progress made in HIV prevention
and treatment.</p>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
