---
title: "Extra Resources"
author: "Junjie Hu"
date: "2023-12-03"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: cosmo
---


## Welcome to Our HIV Resources Page

In the journey to manage and prevent HIV, knowledge is power and support is paramount. This page is dedicated to providing you with comprehensive resources and accessible programs that are pivotal in the treatment and prevention of HIV. Whether you are seeking guidance for yourself, a loved one, or if you're a healthcare provider looking for additional information, you will find a curated collection of links to organizations, support groups, medical insights, and educational materials that align with the latest in HIV care practices.

From cutting-edge treatment options and medication assistance programs to community support networks and preventative education, our resources are carefully selected to empower, inform, and assist. We understand the importance of up-to-date, reliable, and empathetic resources in the fight against HIV, and we strive to help you navigate the path to wellness and resilience. Explore our links to discover the tools and connections that can make a significant difference in the lives of those affected by HIV.

## Treatment
[More info in CDC](https://www.cdc.gov/hiv/basics/livingwithhiv/treatment.html)

## Prevention
[More info in CDC](https://www.cdc.gov/hiv/basics/prevention.html)
