<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Sociodemographic Associated with HIV Infection from 1999 to 2016</title>

<script src="site_libs/header-attrs-2.24/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/navigation-1.1/codefolding.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<script src="site_libs/htmlwidgets-1.6.2/htmlwidgets.js"></script>
<script src="site_libs/plotly-binding-4.10.3/plotly.js"></script>
<script src="site_libs/typedarray-0.1/typedarray.min.js"></script>
<link href="site_libs/crosstalk-1.2.0/css/crosstalk.min.css" rel="stylesheet" />
<script src="site_libs/crosstalk-1.2.0/js/crosstalk.min.js"></script>
<link href="site_libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="site_libs/plotly-main-2.11.1/plotly-latest.min.js"></script>
<link href="site_libs/font-awesome-6.4.2/css/all.min.css" rel="stylesheet" />
<link href="site_libs/font-awesome-6.4.2/css/v4-shims.min.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
</style>




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Global HIV Hub</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="analysis_draft.html">HIV Surveillance</a>
</li>
<li>
  <a href="NHANES.html">Risk Factors</a>
</li>
<li>
  <a href="extra_resources.html">Resources</a>
</li>
<li>
  <a href="https://github.com/IamHJJ/p8105_final_project.github.io">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">

<div class="btn-group pull-right float-right">
<button type="button" class="btn btn-default btn-xs btn-secondary btn-sm dropdown-toggle" data-toggle="dropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
<ul class="dropdown-menu dropdown-menu-right" style="min-width: 50px;">
<li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
<li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
</ul>
</div>



<h1 class="title toc-ignore">Sociodemographic Associated with HIV
Infection from 1999 to 2016</h1>

</div>


<div id="data-sources" class="section level2">
<h2>Data Sources</h2>
<p>The <a href="https://wwwn.cdc.gov/nchs/nhanes/">National Health and
Nutrition Examination Survey</a> is a program of studies designed to
assess the health and nutritional status of adults and children in the
United States. The survey is unique in that it combines interviews and
physical examinations. NHANES is a major program of the National Center
for Health Statistics (NCHS). NCHS is part of the Centers for Disease
Control and Prevention (CDC) and has the responsibility for producing
vital and health statistics for the Nation.</p>
<p>The NHANES interview includes demographic, socioeconomic, dietary,
and health-related questions. The examination component consists of
medical, dental, and physiological measurements, as well as laboratory
tests administered by highly trained medical personnel. In this study,
we used the demographic data, HIV testing, and sexual behavior data from
1999 to 2016 to identify the potential sociodemographic factors
associated with HIV infection status.</p>
</div>
<div id="study-objectives" class="section level2">
<h2>Study Objectives</h2>
<p>Our study’s primary objective is to analyze the NHANES dataset from
1999 to 2016 to identify sociodemographic factors associated with HIV
infection rates in the United States. By examining variables such as
age, gender, race, education level, and marial status, we aim to
illuminate the complex interplay of societal elements influencing HIV
prevalence. This analysis will provide valuable insights into the
demographics most affected by HIV, guiding public health strategies and
resource allocation to improve prevention and treatment programs.
Through this research, we seek to contribute to a more nuanced
understanding of HIV epidemiology that could underpin targeted
interventions and support the reduction of infection disparities across
diverse population groups.</p>
</div>
<div id="import-nhanes-datafiles" class="section level2">
<h2>import NHANES datafiles</h2>
<p>Imported demographic, HIV test, and sexual behavior dataframes 1999 -
2016.</p>
<pre class="r"><code>demo_list = 
  list.files(path = &quot;NHANES/DEMO&quot;, full.names = TRUE) 
hiv_list = 
  list.files(path = &quot;NHANES/HIV&quot;, full.names = TRUE) 
sxq_list = 
  list.files(path = &quot;NHANES/SXQ&quot;, full.names = TRUE) 


load_files = function(x){
  
  filetype =
    str_extract(x, &quot;DEMO|HIV|SXQ&quot;)
  
  year = 
    str_extract(x, &quot;(?&lt;=_)[A-Z]&quot;)
  
data = 
    read_xpt(x) |&gt;
    janitor::clean_names()|&gt;
    mutate(filetype = filetype, year = year)
    
}


demo_list_output = 
  map(demo_list, load_files) 

hiv_list_output = 
  map(hiv_list, load_files) 

sxq_list_output = 
  map(sxq_list, load_files)

join_pair = function(df1, df2) {
  left_join(df1, df2, by = c(&quot;seqn&quot;, &quot;year&quot;))
}


hiv_demo_list = 
  map2(hiv_list_output, demo_list_output, ~join_pair(.x, .y))
  
hiv_demo_sxq_df = 
  map2(hiv_demo_list, sxq_list_output, ~join_pair(.x, .y)) |&gt;
  bind_rows() </code></pre>
<p>Re-coded variables of interest: Restricted particpants’s age between
20 and 49</p>
<pre class="r"><code>cleaned_joined_df = 
  hiv_demo_sxq_df |&gt;
  filter(ridageyr &gt;= 20 &amp; ridageyr &lt;= 49) |&gt;
  mutate(hiv = case_when(
    lbdhi == 1 | lbxhivc == 1 ~ 1,
    lbdhi == 2 | lbxhivc == 2 ~ 2)
    )|&gt; 
  mutate(MSM = case_when(
    year %in% c(&quot;A&quot;,&quot;B&quot;,&quot;C&quot;) ~ sxq220,
    year %in% c(&quot;D&quot;,&quot;E&quot;,&quot;F&quot;,&quot;G&quot;,&quot;H&quot;,&quot;I&quot;) ~ sxq550)
    )|&gt;
   mutate(WSW = case_when(
    year %in% c(&quot;A&quot;,&quot;B&quot;,&quot;C&quot;) ~ sxq150,
    year %in% c(&quot;D&quot;,&quot;E&quot;,&quot;F&quot;,&quot;G&quot;,&quot;H&quot;,&quot;I&quot;) ~ sxq490)
    )|&gt;
  mutate(year = recode(year, 
                       &quot;A&quot; = &quot;1999-2000&quot;,
                       &quot;B&quot; = &quot;2001-2002&quot;,
                       &quot;C&quot; = &quot;2003-2004&quot;,
                       &quot;D&quot; = &quot;2005-2006&quot;,
                       &quot;E&quot; = &quot;2007-2008&quot;,
                       &quot;F&quot; = &quot;2009-2010&quot;,
                       &quot;G&quot; = &quot;2011-2012&quot;,
                       &quot;H&quot; = &quot;2013-2014&quot;,
                       &quot;I&quot; = &quot;2015-2016&quot;),
         hiv = recode(hiv,
                            &quot;1&quot; = &quot;Reactive&quot;,
                            &quot;2&quot; = &quot;Non-reactive&quot;),
         gender = recode(riagendr, 
                         &quot;1&quot; = &quot;Male&quot;,
                         &quot;2&quot; = &quot;Female&quot;),
         age = ridageyr,
         race = recode(ridreth1,
                       &quot;1&quot; = &quot;Mexican American&quot;,
                       &quot;2&quot; = &quot;Other Hispanic&quot;,
                       &quot;3&quot; = &quot;Non-Hispanic White&quot;,
                       &quot;4&quot; = &quot;Non-Hispanic Black&quot;,
                       &quot;5&quot; = &quot;Other Race - Including Multi-Racial&quot;),
         education = recode(dmdeduc2,
                            &quot;1&quot; = &quot;Less than 9th grade&quot;,
                            &quot;2&quot; = &quot;9-11th grade&quot;,
                            &quot;3&quot; = &quot;High school graduate or equivalent&quot;,
                            &quot;4&quot; = &quot;Some college or AA degree&quot;,
                            &quot;5&quot; = &quot;College graduate or above&quot;,
                            &quot;7&quot; = NA_character_,
                            &quot;9&quot; = NA_character_),
         marriage = recode(dmdmartl,
                           &quot;1&quot; = &quot;Married&quot;, 
                           &quot;2&quot; = &quot;Widowed&quot;,
                           &quot;3&quot; = &quot;Divorced&quot;,
                           &quot;4&quot; = &quot;Separated&quot;,
                           &quot;5&quot; = &quot;Never married&quot;,
                           &quot;6&quot; = &quot;Living with partner&quot;,
                           &quot;77&quot; = NA_character_,
                           &quot;99&quot; = NA_character_)
         ) |&gt;
  mutate(samesexcontact = case_when(
    (MSM %in% c(0, 7777, 77777,9999, 99999) | WSW %in% c(0, 7777, 77777, 9999, 99999)) ~ 0,
    (MSM &gt;= 1 &amp; MSM &lt;= 600) | (WSW &gt;= 1 &amp; WSW &lt;= 600) ~ 1
  )) |&gt;
  select(seqn, hiv, age, gender, race, education, marriage, year, samesexcontact)</code></pre>
<p>Visualization - 1 Total number as y-axis value Across race</p>
<pre class="r"><code>cleaned_joined_df %&gt;% 
  filter(hiv == &quot;Reactive&quot;) %&gt;% 
  group_by(race, gender) %&gt;%
  summarize(n = n(), age_mean = round(mean(age), 2)) %&gt;% 
  ungroup() %&gt;% 
  mutate(race = fct_reorder(race, n)) %&gt;% 
  mutate(text_label = str_c(&quot;mean age: &quot;, age_mean)) %&gt;% 
  plot_ly(x = ~race, y = ~n, color = ~gender, type = &quot;bar&quot;, text = ~text_label, colors = &quot;viridis&quot;) %&gt;% 
    layout(
      xaxis = list(title = &quot;Race&quot;),
      yaxis = list(title = &quot;Total Number of HIV Positive Patients&quot;),
      title = &quot;The Total Number of HIV Positive Patients from 1999 to 2016 Across Races&quot;
    )</code></pre>
<pre><code>## `summarise()` has grouped output by
## &#39;race&#39;. You can override using the
## `.groups` argument.</code></pre>
<div class="plotly html-widget html-fill-item-overflow-hidden html-fill-item" id="htmlwidget-dc00a98c05dae1ca7a4f" style="width:672px;height:480px;"></div>
<script type="application/json" data-for="htmlwidget-dc00a98c05dae1ca7a4f">{"x":{"visdat":{"746ce9c54e9":["function () ","plotlyVisDat"]},"cur_data":"746ce9c54e9","attrs":{"746ce9c54e9":{"x":{},"y":{},"text":{},"color":{},"colors":"viridis","alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"type":"bar"}},"layout":{"margin":{"b":40,"l":60,"t":25,"r":10},"xaxis":{"domain":[0,1],"automargin":true,"title":"Race","type":"category","categoryorder":"array","categoryarray":["Other Race - Including Multi-Racial","Other Hispanic","Mexican American","Non-Hispanic White","Non-Hispanic Black"]},"yaxis":{"domain":[0,1],"automargin":true,"title":"Total Number of HIV Positive Patients"},"title":"The Total Number of HIV Positive Patients from 1999 to 2016 Across Races","hovermode":"closest","showlegend":true},"source":"A","config":{"modeBarButtonsToAdd":["hoverclosest","hovercompare"],"showSendToCloud":false},"data":[{"x":["Mexican American","Non-Hispanic Black","Non-Hispanic White","Other Hispanic","Other Race - Including Multi-Racial"],"y":[1,29,2,1,1],"text":["mean age: 40","mean age: 39.41","mean age: 37","mean age: 30","mean age: 47"],"type":"bar","name":"Female","marker":{"color":"rgba(68,1,84,1)","line":{"color":"rgba(68,1,84,1)"}},"textfont":{"color":"rgba(68,1,84,1)"},"error_y":{"color":"rgba(68,1,84,1)"},"error_x":{"color":"rgba(68,1,84,1)"},"xaxis":"x","yaxis":"y","frame":null},{"x":["Mexican American","Non-Hispanic Black","Non-Hispanic White","Other Hispanic"],"y":[11,56,15,8],"text":["mean age: 35.36","mean age: 34.88","mean age: 38.27","mean age: 41.88"],"type":"bar","name":"Male","marker":{"color":"rgba(253,231,37,1)","line":{"color":"rgba(253,231,37,1)"}},"textfont":{"color":"rgba(253,231,37,1)"},"error_y":{"color":"rgba(253,231,37,1)"},"error_x":{"color":"rgba(253,231,37,1)"},"xaxis":"x","yaxis":"y","frame":null}],"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.20000000000000001,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
<p>Visualization - 1-1 Total percent as y-axis value</p>
<pre class="r"><code>cleaned_joined_df %&gt;% 
  drop_na(hiv) %&gt;% 
  group_by(race, gender) %&gt;%
  summarize(total_par = n(), age_mean = round(mean(age), 2), 
            hiv_percent = round(sum(hiv == &quot;Reactive&quot;) / sum(hiv != &quot;Reactive&quot;, hiv == &quot;Reactive&quot;) * 100, 3)) %&gt;%
  ungroup() %&gt;% 
  mutate(race = fct_reorder(race, hiv_percent)) %&gt;% 
  mutate(text_label = str_c(&quot;mean age: &quot;, age_mean)) %&gt;% 
  plot_ly(x = ~race, y = ~hiv_percent, color = ~gender, type = &quot;bar&quot;, text = ~text_label, colors = &quot;viridis&quot;) %&gt;% 
    layout(
      xaxis = list(title = &quot;Race&quot;),
      yaxis = list(title = &quot;Total Percent of HIV Positive Patients&quot;),
      title = &quot;The Total Percent of HIV Positive Patients from 1999 to 2016 Across Races&quot;
    )</code></pre>
<pre><code>## `summarise()` has grouped output by
## &#39;race&#39;. You can override using the
## `.groups` argument.</code></pre>
<div class="plotly html-widget html-fill-item-overflow-hidden html-fill-item" id="htmlwidget-1bb69449341035a4515d" style="width:672px;height:480px;"></div>
<script type="application/json" data-for="htmlwidget-1bb69449341035a4515d">{"x":{"visdat":{"746c7dcb4ba9":["function () ","plotlyVisDat"]},"cur_data":"746c7dcb4ba9","attrs":{"746c7dcb4ba9":{"x":{},"y":{},"text":{},"color":{},"colors":"viridis","alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"type":"bar"}},"layout":{"margin":{"b":40,"l":60,"t":25,"r":10},"xaxis":{"domain":[0,1],"automargin":true,"title":"Race","type":"category","categoryorder":"array","categoryarray":["Other Race - Including Multi-Racial","Non-Hispanic White","Mexican American","Other Hispanic","Non-Hispanic Black"]},"yaxis":{"domain":[0,1],"automargin":true,"title":"Total Percent of HIV Positive Patients"},"title":"The Total Percent of HIV Positive Patients from 1999 to 2016 Across Races","hovermode":"closest","showlegend":true},"source":"A","config":{"modeBarButtonsToAdd":["hoverclosest","hovercompare"],"showSendToCloud":false},"data":[{"x":["Mexican American","Non-Hispanic Black","Non-Hispanic White","Other Hispanic","Other Race - Including Multi-Racial"],"y":[0.039,1.119,0.040000000000000001,0.094,0.089999999999999997],"text":["mean age: 33.52","mean age: 34.39","mean age: 34.34","mean age: 34.06","mean age: 34.39"],"type":"bar","name":"Female","marker":{"color":"rgba(68,1,84,1)","line":{"color":"rgba(68,1,84,1)"}},"textfont":{"color":"rgba(68,1,84,1)"},"error_y":{"color":"rgba(68,1,84,1)"},"error_x":{"color":"rgba(68,1,84,1)"},"xaxis":"x","yaxis":"y","frame":null},{"x":["Mexican American","Non-Hispanic Black","Non-Hispanic White","Other Hispanic","Other Race - Including Multi-Racial"],"y":[0.48999999999999999,2.5350000000000001,0.33600000000000002,0.93500000000000005,0],"text":["mean age: 33.96","mean age: 34.27","mean age: 34.85","mean age: 34.41","mean age: 33.98"],"type":"bar","name":"Male","marker":{"color":"rgba(253,231,37,1)","line":{"color":"rgba(253,231,37,1)"}},"textfont":{"color":"rgba(253,231,37,1)"},"error_y":{"color":"rgba(253,231,37,1)"},"error_x":{"color":"rgba(253,231,37,1)"},"xaxis":"x","yaxis":"y","frame":null}],"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.20000000000000001,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
<p>Visualization 2: by year</p>
<pre class="r"><code>cleaned_joined_df %&gt;% 
  drop_na(hiv) %&gt;% 
  group_by(year, gender) %&gt;% 
  summarize(age_mean = round(mean(age), 2), 
            hiv_percent = round(sum(hiv == &quot;Reactive&quot;) / sum(hiv != &quot;Reactive&quot;, hiv == &quot;Reactive&quot;) * 100, 3)) %&gt;%
  ungroup() %&gt;% 
  mutate(text_label = str_c(&quot;mean age: &quot;, age_mean)) %&gt;% 
  plot_ly(x = ~year, y = ~hiv_percent, color = ~gender, type = &quot;scatter&quot;, mode = &quot;lines+markers&quot;,
          text = ~text_label, colors = &quot;viridis&quot;) %&gt;% 
  layout(
      xaxis = list(title = &quot;Year&quot;),
      yaxis = list(title = &quot;Total Percent of HIV Positive Patients&quot;),
      title = &quot;The Total Percent of HIV Positive Patients from 1999 to 2016&quot;
    )</code></pre>
<pre><code>## `summarise()` has grouped output by
## &#39;year&#39;. You can override using the
## `.groups` argument.</code></pre>
<div class="plotly html-widget html-fill-item-overflow-hidden html-fill-item" id="htmlwidget-7376cb451e42f4e54cfe" style="width:672px;height:480px;"></div>
<script type="application/json" data-for="htmlwidget-7376cb451e42f4e54cfe">{"x":{"visdat":{"746c47812c":["function () ","plotlyVisDat"]},"cur_data":"746c47812c","attrs":{"746c47812c":{"x":{},"y":{},"mode":"lines+markers","text":{},"color":{},"colors":"viridis","alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"type":"scatter"}},"layout":{"margin":{"b":40,"l":60,"t":25,"r":10},"xaxis":{"domain":[0,1],"automargin":true,"title":"Year","type":"category","categoryorder":"array","categoryarray":["1999-2000","2001-2002","2003-2004","2005-2006","2007-2008","2009-2010","2011-2012","2013-2014","2015-2016"]},"yaxis":{"domain":[0,1],"automargin":true,"title":"Total Percent of HIV Positive Patients"},"title":"The Total Percent of HIV Positive Patients from 1999 to 2016","hovermode":"closest","showlegend":true},"source":"A","config":{"modeBarButtonsToAdd":["hoverclosest","hovercompare"],"showSendToCloud":false},"data":[{"x":["1999-2000","2001-2002","2003-2004","2005-2006","2007-2008","2009-2010","2011-2012","2013-2014","2015-2016"],"y":[0.32500000000000001,0.48499999999999999,0.40899999999999997,0.28199999999999997,0.075999999999999998,0.25700000000000001,0.23400000000000001,0.20899999999999999,0.218],"mode":"lines+markers","text":["mean age: 33.6","mean age: 33.44","mean age: 33.73","mean age: 33","mean age: 34.98","mean age: 34.7","mean age: 34.29","mean age: 34.89","mean age: 34.69"],"type":"scatter","name":"Female","marker":{"color":"rgba(68,1,84,1)","line":{"color":"rgba(68,1,84,1)"}},"textfont":{"color":"rgba(68,1,84,1)"},"error_y":{"color":"rgba(68,1,84,1)"},"error_x":{"color":"rgba(68,1,84,1)"},"line":{"color":"rgba(68,1,84,1)"},"xaxis":"x","yaxis":"y","frame":null},{"x":["1999-2000","2001-2002","2003-2004","2005-2006","2007-2008","2009-2010","2011-2012","2013-2014","2015-2016"],"y":[1.325,0.57899999999999996,0.91000000000000003,1.2050000000000001,0.89600000000000002,0.88200000000000001,0.71299999999999997,0.76300000000000001,0.33200000000000002],"mode":"lines+markers","text":["mean age: 34.5","mean age: 34.85","mean age: 33.86","mean age: 34.4","mean age: 34.82","mean age: 34.72","mean age: 33.91","mean age: 34.35","mean age: 34.38"],"type":"scatter","name":"Male","marker":{"color":"rgba(253,231,37,1)","line":{"color":"rgba(253,231,37,1)"}},"textfont":{"color":"rgba(253,231,37,1)"},"error_y":{"color":"rgba(253,231,37,1)"},"error_x":{"color":"rgba(253,231,37,1)"},"line":{"color":"rgba(253,231,37,1)"},"xaxis":"x","yaxis":"y","frame":null}],"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.20000000000000001,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
<p>Visualization 3: Across Education level</p>
<pre class="r"><code>cleaned_joined_df %&gt;% 
  drop_na(hiv) %&gt;% 
  group_by(education, gender) %&gt;%
  summarize(total_par = n(), age_mean = round(mean(age), 2), 
            hiv_percent = round(sum(hiv == &quot;Reactive&quot;) / total_par * 100, 3)) %&gt;%
  ungroup() %&gt;% 
  mutate(education = forcats::fct_relevel(education, c(&quot;Less than 9th grade&quot;, &quot;9-11th grade&quot;, 
                                         &quot;High school graduate or equivalent&quot;, 
                                         &quot;Some college or AA degree&quot;,
                                         &quot;College graduate or above&quot;))) %&gt;% 
  mutate(text_label = str_c(&quot;mean age: &quot;, age_mean)) %&gt;% 
  plot_ly(x = ~education, y = ~hiv_percent, color = ~gender, type = &quot;bar&quot;, text = ~text_label, colors = &quot;viridis&quot;) %&gt;% 
    layout(
      xaxis = list(title = &quot;Education level&quot;),
      yaxis = list(title = &quot;Total Percent of HIV Positive Patients&quot;),
      title = &quot;The Total Percent of HIV Positive Patients from 1999 to 2016 Across Education Level&quot;
    )</code></pre>
<pre><code>## `summarise()` has grouped output by
## &#39;education&#39;. You can override using
## the `.groups` argument.</code></pre>
<pre><code>## Warning: Ignoring 2 observations</code></pre>
<div class="plotly html-widget html-fill-item-overflow-hidden html-fill-item" id="htmlwidget-eda52a5c4af4a50df957" style="width:672px;height:480px;"></div>
<script type="application/json" data-for="htmlwidget-eda52a5c4af4a50df957">{"x":{"visdat":{"746c3c555b6d":["function () ","plotlyVisDat"]},"cur_data":"746c3c555b6d","attrs":{"746c3c555b6d":{"x":{},"y":{},"text":{},"color":{},"colors":"viridis","alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"type":"bar"}},"layout":{"margin":{"b":40,"l":60,"t":25,"r":10},"xaxis":{"domain":[0,1],"automargin":true,"title":"Education level","type":"category","categoryorder":"array","categoryarray":["Less than 9th grade","9-11th grade","High school graduate or equivalent","Some college or AA degree","College graduate or above"]},"yaxis":{"domain":[0,1],"automargin":true,"title":"Total Percent of HIV Positive Patients"},"title":"The Total Percent of HIV Positive Patients from 1999 to 2016 Across Education Level","hovermode":"closest","showlegend":true},"source":"A","config":{"modeBarButtonsToAdd":["hoverclosest","hovercompare"],"showSendToCloud":false},"data":[{"x":["9-11th grade","College graduate or above","High school graduate or equivalent","Less than 9th grade","Some college or AA degree"],"y":[0.60999999999999999,0.068000000000000005,0.39500000000000002,0.216,0.19600000000000001],"text":["mean age: 33.77","mean age: 35.38","mean age: 33.63","mean age: 36.24","mean age: 33.31"],"type":"bar","name":"Female","marker":{"color":"rgba(68,1,84,1)","line":{"color":"rgba(68,1,84,1)"}},"textfont":{"color":"rgba(68,1,84,1)"},"error_y":{"color":"rgba(68,1,84,1)"},"error_x":{"color":"rgba(68,1,84,1)"},"xaxis":"x","yaxis":"y","frame":null},{"x":["9-11th grade","College graduate or above","High school graduate or equivalent","Less than 9th grade","Some college or AA degree"],"y":[1.012,0.56200000000000006,0.72599999999999998,0.45300000000000001,1.1359999999999999],"text":["mean age: 33.73","mean age: 35.96","mean age: 34.07","mean age: 36.19","mean age: 33.49"],"type":"bar","name":"Male","marker":{"color":"rgba(253,231,37,1)","line":{"color":"rgba(253,231,37,1)"}},"textfont":{"color":"rgba(253,231,37,1)"},"error_y":{"color":"rgba(253,231,37,1)"},"error_x":{"color":"rgba(253,231,37,1)"},"xaxis":"x","yaxis":"y","frame":null}],"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.20000000000000001,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
<p>Visualization 4: Across marital status</p>
<pre class="r"><code>cleaned_joined_df %&gt;% 
  drop_na(hiv) %&gt;% 
  group_by(marriage, gender) %&gt;%
  summarize(total_par = n(), age_mean = round(mean(age), 2), 
            hiv_percent = round(sum(hiv == &quot;Reactive&quot;) / sum(hiv != &quot;Reactive&quot;, hiv == &quot;Reactive&quot;) * 100, 3)) %&gt;%
  ungroup() %&gt;% 
  mutate(marriage = fct_reorder(marriage, hiv_percent)) %&gt;% 
  mutate(text_label = str_c(&quot;mean age: &quot;, age_mean)) %&gt;% 
  plot_ly(x = ~marriage, y = ~hiv_percent, color = ~gender, type = &quot;bar&quot;, text = ~text_label, colors = &quot;viridis&quot;) %&gt;% 
    layout(
      xaxis = list(title = &quot;Marital Status&quot;),
      yaxis = list(title = &quot;Total Percent of HIV Positive Patients&quot;),
      title = &quot;The Total Percent of HIV Positive Patients from 1999 to 2016 Across Marital Status&quot;
    )</code></pre>
<pre><code>## `summarise()` has grouped output by
## &#39;marriage&#39;. You can override using
## the `.groups` argument.</code></pre>
<pre><code>## Warning: Ignoring 2 observations</code></pre>
<div class="plotly html-widget html-fill-item-overflow-hidden html-fill-item" id="htmlwidget-782ccb258556e8d1c202" style="width:672px;height:480px;"></div>
<script type="application/json" data-for="htmlwidget-782ccb258556e8d1c202">{"x":{"visdat":{"746c3bcd3f3b":["function () ","plotlyVisDat"]},"cur_data":"746c3bcd3f3b","attrs":{"746c3bcd3f3b":{"x":{},"y":{},"text":{},"color":{},"colors":"viridis","alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"type":"bar"}},"layout":{"margin":{"b":40,"l":60,"t":25,"r":10},"xaxis":{"domain":[0,1],"automargin":true,"title":"Marital Status","type":"category","categoryorder":"array","categoryarray":["Married","Divorced","Living with partner","Never married","Separated","Widowed"]},"yaxis":{"domain":[0,1],"automargin":true,"title":"Total Percent of HIV Positive Patients"},"title":"The Total Percent of HIV Positive Patients from 1999 to 2016 Across Marital Status","hovermode":"closest","showlegend":true},"source":"A","config":{"modeBarButtonsToAdd":["hoverclosest","hovercompare"],"showSendToCloud":false},"data":[{"x":["Divorced","Living with partner","Married","Never married","Separated","Widowed"],"y":[0.29299999999999998,0.379,0.17999999999999999,0.45700000000000002,0.187,0],"text":["mean age: 39.73","mean age: 31.23","mean age: 36.06","mean age: 28.95","mean age: 37.44","mean age: 42.97"],"type":"bar","name":"Female","marker":{"color":"rgba(68,1,84,1)","line":{"color":"rgba(68,1,84,1)"}},"textfont":{"color":"rgba(68,1,84,1)"},"error_y":{"color":"rgba(68,1,84,1)"},"error_x":{"color":"rgba(68,1,84,1)"},"xaxis":"x","yaxis":"y","frame":null},{"x":["Divorced","Living with partner","Married","Never married","Separated","Widowed"],"y":[0.78200000000000003,0.92300000000000004,0.307,1.45,1.8320000000000001,5.556],"text":["mean age: 41.01","mean age: 32.39","mean age: 37.66","mean age: 28.41","mean age: 37.1","mean age: 40.56"],"type":"bar","name":"Male","marker":{"color":"rgba(253,231,37,1)","line":{"color":"rgba(253,231,37,1)"}},"textfont":{"color":"rgba(253,231,37,1)"},"error_y":{"color":"rgba(253,231,37,1)"},"error_x":{"color":"rgba(253,231,37,1)"},"xaxis":"x","yaxis":"y","frame":null}],"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.20000000000000001,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
<p>Visualization 5: Sexual behavior</p>
<pre class="r"><code>cleaned_joined_df %&gt;%
  drop_na(hiv) %&gt;% 
  mutate(samesexcontact = recode(samesexcontact, &quot;0&quot; = &quot;No&quot;, 
                                  &quot;1&quot; = &quot;Yes&quot;)) %&gt;% 
  group_by(samesexcontact, gender) %&gt;% 
  summarize(total_par = n(), age_mean = round(mean(age), 2), hiv_num = sum(hiv == &quot;Reactive&quot;),
            hiv_percent = round(sum(hiv == &quot;Reactive&quot;) / sum(hiv != &quot;Reactive&quot;, hiv == &quot;Reactive&quot;) * 100, 3)) %&gt;% 
  ungroup() %&gt;% 
  mutate(text_label = str_c(&quot;mean age: &quot;, age_mean)) %&gt;% 
  plot_ly(x = ~samesexcontact, y = ~hiv_percent, color = ~gender, type = &quot;bar&quot;, text = ~text_label, colors = &quot;viridis&quot;) %&gt;% 
    layout(
      xaxis = list(title = &quot;Same Sex Sexual Behavior&quot;),
      yaxis = list(title = &quot;Total Percent of HIV Positive Patients&quot;),
      title = &quot;The Total Percent of HIV Positive Patients from 1999 to 2016 Across Sexual Behavior&quot;
    )</code></pre>
<pre><code>## `summarise()` has grouped output by
## &#39;samesexcontact&#39;. You can override
## using the `.groups` argument.</code></pre>
<pre><code>## Warning: Ignoring 2 observations</code></pre>
<div class="plotly html-widget html-fill-item-overflow-hidden html-fill-item" id="htmlwidget-e8703498ae6579be0932" style="width:672px;height:480px;"></div>
<script type="application/json" data-for="htmlwidget-e8703498ae6579be0932">{"x":{"visdat":{"746c33e7468f":["function () ","plotlyVisDat"]},"cur_data":"746c33e7468f","attrs":{"746c33e7468f":{"x":{},"y":{},"text":{},"color":{},"colors":"viridis","alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"type":"bar"}},"layout":{"margin":{"b":40,"l":60,"t":25,"r":10},"xaxis":{"domain":[0,1],"automargin":true,"title":"Same Sex Sexual Behavior","type":"category","categoryorder":"array","categoryarray":["No","Yes"]},"yaxis":{"domain":[0,1],"automargin":true,"title":"Total Percent of HIV Positive Patients"},"title":"The Total Percent of HIV Positive Patients from 1999 to 2016 Across Sexual Behavior","hovermode":"closest","showlegend":true},"source":"A","config":{"modeBarButtonsToAdd":["hoverclosest","hovercompare"],"showSendToCloud":false},"data":[{"x":["No","Yes"],"y":[0.34799999999999998,0.86199999999999999],"text":["mean age: 33.8","mean age: 30.42"],"type":"bar","name":"Female","marker":{"color":"rgba(68,1,84,1)","line":{"color":"rgba(68,1,84,1)"}},"textfont":{"color":"rgba(68,1,84,1)"},"error_y":{"color":"rgba(68,1,84,1)"},"error_x":{"color":"rgba(68,1,84,1)"},"xaxis":"x","yaxis":"y","frame":null},{"x":["No","Yes"],"y":[0.64100000000000001,16.544],"text":["mean age: 34.63","mean age: 33.99"],"type":"bar","name":"Male","marker":{"color":"rgba(253,231,37,1)","line":{"color":"rgba(253,231,37,1)"}},"textfont":{"color":"rgba(253,231,37,1)"},"error_y":{"color":"rgba(253,231,37,1)"},"error_x":{"color":"rgba(253,231,37,1)"},"xaxis":"x","yaxis":"y","frame":null}],"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.20000000000000001,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
<p>Visualization 6: by year, stratified by education level instead of
gender</p>
<pre class="r"><code>cleaned_joined_df %&gt;% 
  drop_na(hiv) %&gt;% 
  group_by(year, education) %&gt;% 
  summarize(age_mean = round(mean(age), 2), 
            hiv_percent = round(sum(hiv == &quot;Reactive&quot;) / sum(hiv != &quot;Reactive&quot;, hiv == &quot;Reactive&quot;) * 100, 3)) %&gt;%
  ungroup() %&gt;% 
  mutate(education = forcats::fct_relevel(education, c(&quot;Less than 9th grade&quot;, &quot;9-11th grade&quot;, 
                                         &quot;High school graduate or equivalent&quot;, 
                                         &quot;Some college or AA degree&quot;,
                                         &quot;College graduate or above&quot;))) %&gt;% 
  mutate(text_label = str_c(&quot;mean age: &quot;, age_mean)) %&gt;% 
  plot_ly(x = ~year, y = ~hiv_percent, color = ~education, type = &quot;scatter&quot;, mode = &quot;lines+markers&quot;,
          text = ~text_label, colors = &quot;viridis&quot;) %&gt;% 
  layout(
      xaxis = list(title = &quot;Year&quot;),
      yaxis = list(title = &quot;Total Percent of HIV Positive Patients&quot;),
      title = &quot;The Total Percent of HIV Positive Patients from 1999 to 2016 by Education Level&quot;
    )</code></pre>
<pre><code>## `summarise()` has grouped output by
## &#39;year&#39;. You can override using the
## `.groups` argument.</code></pre>
<div class="plotly html-widget html-fill-item-overflow-hidden html-fill-item" id="htmlwidget-d2eb932acddefe5e8bb1" style="width:672px;height:480px;"></div>
<script type="application/json" data-for="htmlwidget-d2eb932acddefe5e8bb1">{"x":{"visdat":{"746c256c311d":["function () ","plotlyVisDat"]},"cur_data":"746c256c311d","attrs":{"746c256c311d":{"x":{},"y":{},"mode":"lines+markers","text":{},"color":{},"colors":"viridis","alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"type":"scatter"}},"layout":{"margin":{"b":40,"l":60,"t":25,"r":10},"xaxis":{"domain":[0,1],"automargin":true,"title":"Year","type":"category","categoryorder":"array","categoryarray":["1999-2000","2001-2002","2003-2004","2005-2006","2007-2008","2009-2010","2011-2012","2013-2014","2015-2016"]},"yaxis":{"domain":[0,1],"automargin":true,"title":"Total Percent of HIV Positive Patients"},"title":"The Total Percent of HIV Positive Patients from 1999 to 2016 by Education Level","hovermode":"closest","showlegend":true},"source":"A","config":{"modeBarButtonsToAdd":["hoverclosest","hovercompare"],"showSendToCloud":false},"data":[{"x":["1999-2000","2001-2002","2003-2004","2005-2006","2007-2008","2009-2010","2011-2012","2013-2014","2015-2016"],"y":[0.437,0.35999999999999999,0,0.43099999999999999,0.495,0.38500000000000001,0.80600000000000005,0,0],"mode":"lines+markers","text":["mean age: 35.63","mean age: 35.03","mean age: 35.82","mean age: 34.25","mean age: 36.92","mean age: 36.98","mean age: 37.41","mean age: 38.44","mean age: 37.28"],"type":"scatter","name":"Less than 9th grade","marker":{"color":"rgba(68,1,84,1)","line":{"color":"rgba(68,1,84,1)"}},"textfont":{"color":"rgba(68,1,84,1)"},"error_y":{"color":"rgba(68,1,84,1)"},"error_x":{"color":"rgba(68,1,84,1)"},"line":{"color":"rgba(68,1,84,1)"},"xaxis":"x","yaxis":"y","frame":null},{"x":["1999-2000","2001-2002","2003-2004","2005-2006","2007-2008","2009-2010","2011-2012","2013-2014","2015-2016"],"y":[1.345,0.92200000000000004,0.53900000000000003,1.4890000000000001,0.82799999999999996,0.64200000000000002,0.61699999999999999,0.54300000000000004,0],"mode":"lines+markers","text":["mean age: 33.74","mean age: 33.05","mean age: 32.24","mean age: 32.05","mean age: 34.12","mean age: 34.65","mean age: 35.13","mean age: 33.95","mean age: 35.28"],"type":"scatter","name":"9-11th grade","marker":{"color":"rgba(59,82,139,1)","line":{"color":"rgba(59,82,139,1)"}},"textfont":{"color":"rgba(59,82,139,1)"},"error_y":{"color":"rgba(59,82,139,1)"},"error_x":{"color":"rgba(59,82,139,1)"},"line":{"color":"rgba(59,82,139,1)"},"xaxis":"x","yaxis":"y","frame":null},{"x":["1999-2000","2001-2002","2003-2004","2005-2006","2007-2008","2009-2010","2011-2012","2013-2014","2015-2016"],"y":[0.191,0.46899999999999997,1.631,0,0.63400000000000001,0.89800000000000002,0.60399999999999998,0.16600000000000001,0.374],"mode":"lines+markers","text":["mean age: 33.34","mean age: 33.23","mean age: 34.2","mean age: 33.18","mean age: 34.45","mean age: 33.88","mean age: 34.38","mean age: 34.27","mean age: 33.78"],"type":"scatter","name":"High school graduate or equivalent","marker":{"color":"rgba(33,144,141,1)","line":{"color":"rgba(33,144,141,1)"}},"textfont":{"color":"rgba(33,144,141,1)"},"error_y":{"color":"rgba(33,144,141,1)"},"error_x":{"color":"rgba(33,144,141,1)"},"line":{"color":"rgba(33,144,141,1)"},"xaxis":"x","yaxis":"y","frame":null},{"x":["1999-2000","2001-2002","2003-2004","2005-2006","2007-2008","2009-2010","2011-2012","2013-2014","2015-2016"],"y":[1.1930000000000001,0.51700000000000002,0.27800000000000002,1.0840000000000001,0.26900000000000002,0.224,0.58199999999999996,0.86099999999999999,0.48099999999999998],"mode":"lines+markers","text":["mean age: 32.87","mean age: 34.01","mean age: 33.56","mean age: 33","mean age: 34.3","mean age: 33.76","mean age: 32","mean age: 33.43","mean age: 33.58"],"type":"scatter","name":"Some college or AA degree","marker":{"color":"rgba(93,200,99,1)","line":{"color":"rgba(93,200,99,1)"}},"textfont":{"color":"rgba(93,200,99,1)"},"error_y":{"color":"rgba(93,200,99,1)"},"error_x":{"color":"rgba(93,200,99,1)"},"line":{"color":"rgba(93,200,99,1)"},"xaxis":"x","yaxis":"y","frame":null},{"x":["1999-2000","2001-2002","2003-2004","2005-2006","2007-2008","2009-2010","2011-2012","2013-2014","2015-2016"],"y":[0.23699999999999999,0.38200000000000001,0.215,0.373,0.20399999999999999,0.64000000000000001,0.13500000000000001,0.27600000000000002,0.13700000000000001],"mode":"lines+markers","text":["mean age: 35.81","mean age: 35.58","mean age: 34.19","mean age: 36.01","mean age: 36.35","mean age: 36.02","mean age: 35.35","mean age: 36.19","mean age: 35.16"],"type":"scatter","name":"College graduate or above","marker":{"color":"rgba(253,231,37,1)","line":{"color":"rgba(253,231,37,1)"}},"textfont":{"color":"rgba(253,231,37,1)"},"error_y":{"color":"rgba(253,231,37,1)"},"error_x":{"color":"rgba(253,231,37,1)"},"line":{"color":"rgba(253,231,37,1)"},"xaxis":"x","yaxis":"y","frame":null}],"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.20000000000000001,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
<p>Visualization 7: by year, stratified by race</p>
<pre class="r"><code>cleaned_joined_df %&gt;% 
  drop_na(hiv) %&gt;% 
  group_by(year, race) %&gt;% 
  summarize(age_mean = round(mean(age), 2), 
            hiv_percent = round(sum(hiv == &quot;Reactive&quot;) / sum(hiv != &quot;Reactive&quot;, hiv == &quot;Reactive&quot;) * 100, 3)) %&gt;%
  ungroup() %&gt;% 
  mutate(race = fct_reorder(race, hiv_percent)) %&gt;% 
  mutate(text_label = str_c(&quot;mean age: &quot;, age_mean)) %&gt;% 
  plot_ly(x = ~year, y = ~hiv_percent, color = ~race, type = &quot;scatter&quot;, mode = &quot;lines+markers&quot;,
          text = ~text_label, colors = &quot;viridis&quot;) %&gt;% 
  layout(
      xaxis = list(title = &quot;Year&quot;),
      yaxis = list(title = &quot;Total Percent of HIV Positive Patients&quot;),
      title = &quot;The Total Percent of HIV Positive Patients from 1999 to 2016 by Race&quot;
    )</code></pre>
<pre><code>## `summarise()` has grouped output by
## &#39;year&#39;. You can override using the
## `.groups` argument.</code></pre>
<div class="plotly html-widget html-fill-item-overflow-hidden html-fill-item" id="htmlwidget-ac337ebfd308cb8ed215" style="width:672px;height:480px;"></div>
<script type="application/json" data-for="htmlwidget-ac337ebfd308cb8ed215">{"x":{"visdat":{"746c714c4329":["function () ","plotlyVisDat"]},"cur_data":"746c714c4329","attrs":{"746c714c4329":{"x":{},"y":{},"mode":"lines+markers","text":{},"color":{},"colors":"viridis","alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"type":"scatter"}},"layout":{"margin":{"b":40,"l":60,"t":25,"r":10},"xaxis":{"domain":[0,1],"automargin":true,"title":"Year","type":"category","categoryorder":"array","categoryarray":["1999-2000","2001-2002","2003-2004","2005-2006","2007-2008","2009-2010","2011-2012","2013-2014","2015-2016"]},"yaxis":{"domain":[0,1],"automargin":true,"title":"Total Percent of HIV Positive Patients"},"title":"The Total Percent of HIV Positive Patients from 1999 to 2016 by Race","hovermode":"closest","showlegend":true},"source":"A","config":{"modeBarButtonsToAdd":["hoverclosest","hovercompare"],"showSendToCloud":false},"data":[{"x":["1999-2000","2001-2002","2003-2004","2005-2006","2007-2008","2009-2010","2011-2012","2013-2014","2015-2016"],"y":[0,0,0,0,0.83999999999999997,0,0,0,0],"mode":"lines+markers","text":["mean age: 32.78","mean age: 32.32","mean age: 31.91","mean age: 35.13","mean age: 34.67","mean age: 33.9","mean age: 33.9","mean age: 34.81","mean age: 34.76"],"type":"scatter","name":"Other Race - Including Multi-Racial","marker":{"color":"rgba(68,1,84,1)","line":{"color":"rgba(68,1,84,1)"}},"textfont":{"color":"rgba(68,1,84,1)"},"error_y":{"color":"rgba(68,1,84,1)"},"error_x":{"color":"rgba(68,1,84,1)"},"line":{"color":"rgba(68,1,84,1)"},"xaxis":"x","yaxis":"y","frame":null},{"x":["1999-2000","2001-2002","2003-2004","2005-2006","2007-2008","2009-2010","2011-2012","2013-2014","2015-2016"],"y":[0.22500000000000001,0.083000000000000004,0.27600000000000002,0.35999999999999999,0.091999999999999998,0.076999999999999999,0.111,0.090999999999999998,0.39600000000000002],"mode":"lines+markers","text":["mean age: 33.85","mean age: 34.47","mean age: 34.03","mean age: 34","mean age: 35.85","mean age: 35.07","mean age: 34.76","mean age: 34.52","mean age: 34.43"],"type":"scatter","name":"Non-Hispanic White","marker":{"color":"rgba(59,82,139,1)","line":{"color":"rgba(59,82,139,1)"}},"textfont":{"color":"rgba(59,82,139,1)"},"error_y":{"color":"rgba(59,82,139,1)"},"error_x":{"color":"rgba(59,82,139,1)"},"line":{"color":"rgba(59,82,139,1)"},"xaxis":"x","yaxis":"y","frame":null},{"x":["1999-2000","2001-2002","2003-2004","2005-2006","2007-2008","2009-2010","2011-2012","2013-2014","2015-2016"],"y":[0,0.58599999999999997,0.40100000000000002,0.156,0.184,0.503,0.32800000000000001,0,0],"mode":"lines+markers","text":["mean age: 33.7","mean age: 33.17","mean age: 33.54","mean age: 32.4","mean age: 33.55","mean age: 34.41","mean age: 34.43","mean age: 35.25","mean age: 34.16"],"type":"scatter","name":"Mexican American","marker":{"color":"rgba(33,144,141,1)","line":{"color":"rgba(33,144,141,1)"}},"textfont":{"color":"rgba(33,144,141,1)"},"error_y":{"color":"rgba(33,144,141,1)"},"error_x":{"color":"rgba(33,144,141,1)"},"line":{"color":"rgba(33,144,141,1)"},"xaxis":"x","yaxis":"y","frame":null},{"x":["1999-2000","2001-2002","2003-2004","2005-2006","2007-2008","2009-2010","2011-2012","2013-2014","2015-2016"],"y":[0,1.575,1.1240000000000001,0.88500000000000001,0.65800000000000003,0.60199999999999998,0.433,0,0],"mode":"lines+markers","text":["mean age: 32.52","mean age: 34.47","mean age: 33.91","mean age: 32.58","mean age: 34.53","mean age: 35.03","mean age: 33.42","mean age: 34.77","mean age: 34.59"],"type":"scatter","name":"Other Hispanic","marker":{"color":"rgba(93,200,99,1)","line":{"color":"rgba(93,200,99,1)"}},"textfont":{"color":"rgba(93,200,99,1)"},"error_y":{"color":"rgba(93,200,99,1)"},"error_x":{"color":"rgba(93,200,99,1)"},"line":{"color":"rgba(93,200,99,1)"},"xaxis":"x","yaxis":"y","frame":null},{"x":["1999-2000","2001-2002","2003-2004","2005-2006","2007-2008","2009-2010","2011-2012","2013-2014","2015-2016"],"y":[3.4009999999999998,1.2889999999999999,1.6419999999999999,2,1.417,2.028,1.4930000000000001,2.2989999999999999,0.71899999999999997],"mode":"lines+markers","text":["mean age: 35.49","mean age: 34.62","mean age: 33.86","mean age: 34.17","mean age: 34.6","mean age: 34.23","mean age: 33.37","mean age: 34.16","mean age: 34.85"],"type":"scatter","name":"Non-Hispanic Black","marker":{"color":"rgba(253,231,37,1)","line":{"color":"rgba(253,231,37,1)"}},"textfont":{"color":"rgba(253,231,37,1)"},"error_y":{"color":"rgba(253,231,37,1)"},"error_x":{"color":"rgba(253,231,37,1)"},"line":{"color":"rgba(253,231,37,1)"},"xaxis":"x","yaxis":"y","frame":null}],"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.20000000000000001,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
<p>Visualization 8: by year, stratified by marital status</p>
<pre class="r"><code>cleaned_joined_df %&gt;% 
  drop_na(hiv, marriage) %&gt;% 
  group_by(year, marriage) %&gt;% 
  summarize(age_mean = round(mean(age), 2), 
            hiv_percent = round(sum(hiv == &quot;Reactive&quot;) / sum(hiv != &quot;Reactive&quot;, hiv == &quot;Reactive&quot;) * 100, 3)) %&gt;%
  ungroup() %&gt;% 
  mutate(text_label = str_c(&quot;mean age: &quot;, age_mean)) %&gt;% 
  plot_ly(x = ~year, y = ~hiv_percent, color = ~marriage, type = &quot;scatter&quot;, mode = &quot;lines+markers&quot;,
          text = ~text_label, colors = &quot;viridis&quot;) %&gt;% 
  layout(
      xaxis = list(title = &quot;Year&quot;),
      yaxis = list(title = &quot;Total Percent of HIV Positive Patients&quot;),
      title = &quot;The Total Percent of HIV Positive Patients from 1999 to 2016 by Marital Status&quot;
    )</code></pre>
<pre><code>## `summarise()` has grouped output by
## &#39;year&#39;. You can override using the
## `.groups` argument.</code></pre>
<div class="plotly html-widget html-fill-item-overflow-hidden html-fill-item" id="htmlwidget-7b20b0c7ba05a3676012" style="width:672px;height:480px;"></div>
<script type="application/json" data-for="htmlwidget-7b20b0c7ba05a3676012">{"x":{"visdat":{"746c483e69c":["function () ","plotlyVisDat"]},"cur_data":"746c483e69c","attrs":{"746c483e69c":{"x":{},"y":{},"mode":"lines+markers","text":{},"color":{},"colors":"viridis","alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"type":"scatter"}},"layout":{"margin":{"b":40,"l":60,"t":25,"r":10},"xaxis":{"domain":[0,1],"automargin":true,"title":"Year","type":"category","categoryorder":"array","categoryarray":["1999-2000","2001-2002","2003-2004","2005-2006","2007-2008","2009-2010","2011-2012","2013-2014","2015-2016"]},"yaxis":{"domain":[0,1],"automargin":true,"title":"Total Percent of HIV Positive Patients"},"title":"The Total Percent of HIV Positive Patients from 1999 to 2016 by Marital Status","hovermode":"closest","showlegend":true},"source":"A","config":{"modeBarButtonsToAdd":["hoverclosest","hovercompare"],"showSendToCloud":false},"data":[{"x":["1999-2000","2001-2002","2003-2004","2005-2006","2007-2008","2009-2010","2011-2012","2013-2014","2015-2016"],"y":[1.333,0.60199999999999998,1.093,1.266,0.46700000000000003,0,0,0,0],"mode":"lines+markers","text":["mean age: 39.83","mean age: 39.85","mean age: 39.79","mean age: 39.83","mean age: 40.69","mean age: 40.13","mean age: 40.37","mean age: 40.8","mean age: 40.46"],"type":"scatter","name":"Divorced","marker":{"color":"rgba(68,1,84,1)","line":{"color":"rgba(68,1,84,1)"}},"textfont":{"color":"rgba(68,1,84,1)"},"error_y":{"color":"rgba(68,1,84,1)"},"error_x":{"color":"rgba(68,1,84,1)"},"line":{"color":"rgba(68,1,84,1)"},"xaxis":"x","yaxis":"y","frame":null},{"x":["1999-2000","2001-2002","2003-2004","2005-2006","2007-2008","2009-2010","2011-2012","2013-2014","2015-2016"],"y":[1.4179999999999999,0,1.2769999999999999,1.4790000000000001,1.0069999999999999,0.80000000000000004,0,0.32400000000000001,0],"mode":"lines+markers","text":["mean age: 31.79","mean age: 31.97","mean age: 31.48","mean age: 31.39","mean age: 32.44","mean age: 31.5","mean age: 32.43","mean age: 31.47","mean age: 31.86"],"type":"scatter","name":"Living with partner","marker":{"color":"rgba(65,68,135,1)","line":{"color":"rgba(65,68,135,1)"}},"textfont":{"color":"rgba(65,68,135,1)"},"error_y":{"color":"rgba(65,68,135,1)"},"error_x":{"color":"rgba(65,68,135,1)"},"line":{"color":"rgba(65,68,135,1)"},"xaxis":"x","yaxis":"y","frame":null},{"x":["1999-2000","2001-2002","2003-2004","2005-2006","2007-2008","2009-2010","2011-2012","2013-2014","2015-2016"],"y":[0.19500000000000001,0.20399999999999999,0.17499999999999999,0.28899999999999998,0.24199999999999999,0.36599999999999999,0.26500000000000001,0.14899999999999999,0.248],"mode":"lines+markers","text":["mean age: 35.73","mean age: 36.01","mean age: 36.01","mean age: 35.44","mean age: 37.45","mean age: 37.75","mean age: 37.31","mean age: 37.82","mean age: 37.55"],"type":"scatter","name":"Married","marker":{"color":"rgba(42,120,142,1)","line":{"color":"rgba(42,120,142,1)"}},"textfont":{"color":"rgba(42,120,142,1)"},"error_y":{"color":"rgba(42,120,142,1)"},"error_x":{"color":"rgba(42,120,142,1)"},"line":{"color":"rgba(42,120,142,1)"},"xaxis":"x","yaxis":"y","frame":null},{"x":["1999-2000","2001-2002","2003-2004","2005-2006","2007-2008","2009-2010","2011-2012","2013-2014","2015-2016"],"y":[1.143,1.3680000000000001,0.91200000000000003,1.1399999999999999,0.58699999999999997,0.75900000000000001,1.0609999999999999,1.252,0.54600000000000004],"mode":"lines+markers","text":["mean age: 28.7","mean age: 28.33","mean age: 28.41","mean age: 28.69","mean age: 28.94","mean age: 28.46","mean age: 28.75","mean age: 28.66","mean age: 29.07"],"type":"scatter","name":"Never married","marker":{"color":"rgba(34,168,132,1)","line":{"color":"rgba(34,168,132,1)"}},"textfont":{"color":"rgba(34,168,132,1)"},"error_y":{"color":"rgba(34,168,132,1)"},"error_x":{"color":"rgba(34,168,132,1)"},"line":{"color":"rgba(34,168,132,1)"},"xaxis":"x","yaxis":"y","frame":null},{"x":["1999-2000","2001-2002","2003-2004","2005-2006","2007-2008","2009-2010","2011-2012","2013-2014","2015-2016"],"y":[1.923,1.01,1.266,0,1,0.90100000000000002,0,0,0],"mode":"lines+markers","text":["mean age: 36.6","mean age: 38.08","mean age: 37.05","mean age: 36.51","mean age: 37.45","mean age: 38.81","mean age: 37.67","mean age: 35.11","mean age: 37.84"],"type":"scatter","name":"Separated","marker":{"color":"rgba(122,209,81,1)","line":{"color":"rgba(122,209,81,1)"}},"textfont":{"color":"rgba(122,209,81,1)"},"error_y":{"color":"rgba(122,209,81,1)"},"error_x":{"color":"rgba(122,209,81,1)"},"line":{"color":"rgba(122,209,81,1)"},"xaxis":"x","yaxis":"y","frame":null},{"x":["1999-2000","2001-2002","2003-2004","2005-2006","2007-2008","2009-2010","2011-2012","2013-2014","2015-2016"],"y":[0,0,5,0,0,5,0,0,0],"mode":"lines+markers","text":["mean age: 41.12","mean age: 41.27","mean age: 42.8","mean age: 42.6","mean age: 43.94","mean age: 42","mean age: 42.33","mean age: 43.33","mean age: 42.28"],"type":"scatter","name":"Widowed","marker":{"color":"rgba(253,231,37,1)","line":{"color":"rgba(253,231,37,1)"}},"textfont":{"color":"rgba(253,231,37,1)"},"error_y":{"color":"rgba(253,231,37,1)"},"error_x":{"color":"rgba(253,231,37,1)"},"line":{"color":"rgba(253,231,37,1)"},"xaxis":"x","yaxis":"y","frame":null}],"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.20000000000000001,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
<p>Visualization 9: by year, stratified by Sexual behavior</p>
<pre class="r"><code>cleaned_joined_df %&gt;% 
  drop_na(hiv, samesexcontact) %&gt;% 
  mutate(samesexcontact = recode(samesexcontact, &quot;0&quot; = &quot;No&quot;, 
                                  &quot;1&quot; = &quot;Yes&quot;)) %&gt;% 
  group_by(year, samesexcontact) %&gt;% 
  summarize(age_mean = round(mean(age), 2), 
            hiv_percent = round(sum(hiv == &quot;Reactive&quot;) / sum(hiv != &quot;Reactive&quot;, hiv == &quot;Reactive&quot;) * 100, 3)) %&gt;%
  ungroup() %&gt;% 
  mutate(text_label = str_c(&quot;mean age: &quot;, age_mean)) %&gt;% 
  plot_ly(x = ~year, y = ~hiv_percent, color = ~samesexcontact, type = &quot;scatter&quot;, mode = &quot;lines+markers&quot;,
          text = ~text_label, colors = &quot;viridis&quot;) %&gt;% 
  layout(
      xaxis = list(title = &quot;Year&quot;),
      yaxis = list(title = &quot;Total Percent of HIV Positive Patients&quot;),
      title = &quot;The Total Percent of HIV Positive Patients from 1999 to 2016 by Sexual Behavior&quot;
    )</code></pre>
<pre><code>## `summarise()` has grouped output by
## &#39;year&#39;. You can override using the
## `.groups` argument.</code></pre>
<div class="plotly html-widget html-fill-item-overflow-hidden html-fill-item" id="htmlwidget-fec5d8415f4340c2541c" style="width:672px;height:480px;"></div>
<script type="application/json" data-for="htmlwidget-fec5d8415f4340c2541c">{"x":{"visdat":{"746c3da72257":["function () ","plotlyVisDat"]},"cur_data":"746c3da72257","attrs":{"746c3da72257":{"x":{},"y":{},"mode":"lines+markers","text":{},"color":{},"colors":"viridis","alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"type":"scatter"}},"layout":{"margin":{"b":40,"l":60,"t":25,"r":10},"xaxis":{"domain":[0,1],"automargin":true,"title":"Year","type":"category","categoryorder":"array","categoryarray":["1999-2000","2001-2002","2003-2004","2005-2006","2007-2008","2009-2010","2011-2012","2013-2014","2015-2016"]},"yaxis":{"domain":[0,1],"automargin":true,"title":"Total Percent of HIV Positive Patients"},"title":"The Total Percent of HIV Positive Patients from 1999 to 2016 by Sexual Behavior","hovermode":"closest","showlegend":true},"source":"A","config":{"modeBarButtonsToAdd":["hoverclosest","hovercompare"],"showSendToCloud":false},"data":[{"x":["1999-2000","2001-2002","2003-2004","2005-2006","2007-2008","2009-2010","2011-2012","2013-2014","2015-2016"],"y":[0.65000000000000002,0.316,0.51000000000000001,1,0.36499999999999999,0,1.835,0,0],"mode":"lines+markers","text":["mean age: 34.17","mean age: 34.48","mean age: 34.02","mean age: 33.98","mean age: 34.28","mean age: 34.34","mean age: 33.82","mean age: 33.41","mean age: 32.31"],"type":"scatter","name":"No","marker":{"color":"rgba(68,1,84,1)","line":{"color":"rgba(68,1,84,1)"}},"textfont":{"color":"rgba(68,1,84,1)"},"error_y":{"color":"rgba(68,1,84,1)"},"error_x":{"color":"rgba(68,1,84,1)"},"line":{"color":"rgba(68,1,84,1)"},"xaxis":"x","yaxis":"y","frame":null},{"x":["1999-2000","2001-2002","2003-2004","2005-2006","2007-2008","2009-2010","2011-2012","2013-2014","2015-2016"],"y":[8,10.345000000000001,5.3570000000000002,9.5239999999999991,8.6959999999999997,4.7619999999999996,8.4510000000000005,9.1950000000000003,6.0979999999999999],"mode":"lines+markers","text":["mean age: 33.62","mean age: 32.83","mean age: 34.18","mean age: 33.79","mean age: 32.45","mean age: 31.68","mean age: 31.28","mean age: 29.38","mean age: 30.83"],"type":"scatter","name":"Yes","marker":{"color":"rgba(253,231,37,1)","line":{"color":"rgba(253,231,37,1)"}},"textfont":{"color":"rgba(253,231,37,1)"},"error_y":{"color":"rgba(253,231,37,1)"},"error_x":{"color":"rgba(253,231,37,1)"},"line":{"color":"rgba(253,231,37,1)"},"xaxis":"x","yaxis":"y","frame":null}],"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.20000000000000001,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
</div>
<div id="logistic-regression" class="section level2">
<h2>logistic regression</h2>
<div id="set-the-reference-group" class="section level3">
<h3>Set the reference group</h3>
<pre class="r"><code>cleaned_regression_df= 
   cleaned_joined_df |&gt; 
   mutate(
      hiv_outcome = ifelse(hiv == &quot;Reactive&quot;, 1, ifelse(hiv == &quot;Non-reactive&quot;, 0, NA)),
      education = forcats::fct_relevel(education, c(&quot;Less than 9th grade&quot;, &quot;9-11th grade&quot;, &quot;High school graduate or equivalent&quot;, &quot;Some college or AA degree&quot;, &quot;College graduate or above&quot;)),
      race = forcats::fct_relevel(race, c(&quot;Non-Hispanic White&quot;, &quot;Mexican American&quot;, &quot;Non-Hispanic Black&quot;, &quot;Other Hispanic&quot;, &quot;Other Race - Including Multi-Racial&quot;)),
      marriage = forcats::fct_relevel(marriage, c(&quot;Married&quot;, &quot;Widowed&quot;, &quot;Divorced&quot;, &quot;Separated&quot;, &quot;Never married&quot;, &quot;Living with partner&quot;))
         )</code></pre>
</div>
<div id="bivariate-analysis" class="section level3">
<h3>Bivariate analysis</h3>
<pre class="r"><code>variables = c(&quot;age&quot;,&quot;gender&quot;,&quot;education&quot;,&quot;race&quot;,&quot;samesexcontact&quot;,&quot;marriage&quot;)

fit_and_summarize &lt;- function(var) {
  model = glm(as.formula(paste(&quot;hiv_outcome~&quot;, var)), data = cleaned_regression_df, family = binomial()) |&gt;
  broom::tidy()
}

model_summaries = 
  map(variables, fit_and_summarize) |&gt;
  bind_rows() |&gt;
  filter(p.value &lt;= 0.008 &amp; term != &quot;(Intercept)&quot;)

model_summaries |&gt;
  select(term, estimate, p.value) |&gt;
  knitr::kable(digits = 3)</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">estimate</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">age</td>
<td align="right">0.037</td>
<td align="right">0.001</td>
</tr>
<tr class="even">
<td align="left">genderMale</td>
<td align="right">1.107</td>
<td align="right">0.000</td>
</tr>
<tr class="odd">
<td align="left">raceNon-Hispanic Black</td>
<td align="right">2.302</td>
<td align="right">0.000</td>
</tr>
<tr class="even">
<td align="left">samesexcontact</td>
<td align="right">2.854</td>
<td align="right">0.000</td>
</tr>
<tr class="odd">
<td align="left">marriageNever married</td>
<td align="right">1.407</td>
<td align="right">0.000</td>
</tr>
<tr class="even">
<td align="left">marriageLiving with partner</td>
<td align="right">1.004</td>
<td align="right">0.001</td>
</tr>
</tbody>
</table>
<p>Because I am conducting 6 logistic tests, the Bonferroni-corrected
significance level would be 0.05/6 = 0.008. Variables <code>age</code>,
<code>gender</code>, <code>race</code>, <code>samesexcontact</code>,
<code>marriage</code> were found significant associated with HIV
infection status, at 0.8% level of significance. Therefore, these
variables were included to the final model.</p>
</div>
<div id="the-final-model" class="section level3">
<h3>The final model</h3>
<pre class="r"><code>fit_regression = cleaned_regression_df |&gt; 
  glm(hiv_outcome ~ samesexcontact + gender + age + race + marriage, data = _, family = binomial()) 

fit_regression|&gt; 
  broom::tidy() |&gt; 
  mutate(OR = exp(estimate)) |&gt; 
  select(term, estimate, OR, p.value)|&gt; 
  knitr::kable(digits = 3)</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">estimate</th>
<th align="right">OR</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">-10.460</td>
<td align="right">0.000</td>
<td align="right">0.000</td>
</tr>
<tr class="even">
<td align="left">samesexcontact</td>
<td align="right">2.834</td>
<td align="right">17.020</td>
<td align="right">0.000</td>
</tr>
<tr class="odd">
<td align="left">genderMale</td>
<td align="right">1.820</td>
<td align="right">6.171</td>
<td align="right">0.000</td>
</tr>
<tr class="even">
<td align="left">age</td>
<td align="right">0.056</td>
<td align="right">1.058</td>
<td align="right">0.000</td>
</tr>
<tr class="odd">
<td align="left">raceMexican American</td>
<td align="right">0.455</td>
<td align="right">1.576</td>
<td align="right">0.324</td>
</tr>
<tr class="even">
<td align="left">raceNon-Hispanic Black</td>
<td align="right">2.072</td>
<td align="right">7.941</td>
<td align="right">0.000</td>
</tr>
<tr class="odd">
<td align="left">raceOther Hispanic</td>
<td align="right">1.245</td>
<td align="right">3.473</td>
<td align="right">0.009</td>
</tr>
<tr class="even">
<td align="left">raceOther Race - Including Multi-Racial</td>
<td align="right">-14.286</td>
<td align="right">0.000</td>
<td align="right">0.978</td>
</tr>
<tr class="odd">
<td align="left">marriageWidowed</td>
<td align="right">2.036</td>
<td align="right">7.661</td>
<td align="right">0.066</td>
</tr>
<tr class="even">
<td align="left">marriageDivorced</td>
<td align="right">1.138</td>
<td align="right">3.121</td>
<td align="right">0.036</td>
</tr>
<tr class="odd">
<td align="left">marriageSeparated</td>
<td align="right">1.406</td>
<td align="right">4.080</td>
<td align="right">0.020</td>
</tr>
<tr class="even">
<td align="left">marriageNever married</td>
<td align="right">1.341</td>
<td align="right">3.823</td>
<td align="right">0.002</td>
</tr>
<tr class="odd">
<td align="left">marriageLiving with partner</td>
<td align="right">1.033</td>
<td align="right">2.811</td>
<td align="right">0.040</td>
</tr>
</tbody>
</table>
<p><strong>Logistic regression results:</strong></p>
<ul>
<li>The logistic regression analysis reveals several key risk factors
associated with HIV in the US.
<ul>
<li>Individuals reporting same-sex contacts exhibit a significant
increase in the odds of being HIV positive (OR = 17.020), emphasizing
the importance of considering sexual behavior in HIV risk
assessment.</li>
<li>Gender is also a significant predictor, with males having 6.171
times higher odds of being HIV positive compared to females.</li>
<li>Age demonstrates a positive association, indicating a slight
increase in HIV odds with 1-year increase in age (OR = 1.058).</li>
<li>Among racial categories, Non-Hispanic Black individuals show the
highest risk (OR = 7.941), while Mexican Americans do not exhibit a
statistically significant association.</li>
<li>Regarding marital status, divorced, separated, and never married
individuals display elevated odds of being HIV positive, suggesting that
certain relationship statuses may contribute to increased
vulnerability.</li>
</ul></li>
<li>These findings underscore the complex interplay of demographic
factors in HIV risk and contribute valuable insights for targeted
prevention and intervention strategies.</li>
</ul>
</div>
<div id="bootstrap" class="section level3">
<h3>Bootstrap</h3>
<pre class="r"><code>bootstrap_df =
  cleaned_regression_df |&gt; 
  bootstrap(n = 500) |&gt; 
  mutate(
    models = map(.x = strap, ~glm(hiv_outcome ~ samesexcontact + gender + age + race + marriage, data = .x, family = binomial()) ),
    results = map(models, broom::tidy)) |&gt; 
  select(-strap, -models) |&gt; 
  unnest(results) |&gt; 
  group_by(term) |&gt; 
  mutate(OR = exp(estimate))</code></pre>
</div>
<div id="distribution-of-estimates-under-repeated-sampling"
class="section level3">
<h3>Distribution of estimates under repeated sampling</h3>
<pre class="r"><code>bootstrap_df|&gt; 
  filter(term == &quot;age&quot;) |&gt; 
  ggplot(aes(x = estimate))+
  geom_density() +
  facet_wrap(.~ term)  </code></pre>
<p><img src="NHANES_files/figure-html/unnamed-chunk-17-1.png" width="672" /></p>
<pre class="r"><code>bootstrap_df|&gt; 
  filter(term != &quot;age&quot;) |&gt; 
  ggplot(aes(x = estimate))+
  geom_density() +
  facet_wrap(.~ term)</code></pre>
<p><img src="NHANES_files/figure-html/unnamed-chunk-17-2.png" width="672" /></p>
<ul>
<li>This is the uncertainty that we would get in this dataset if we do
repeated sampling</li>
</ul>
</div>
<div id="bootstrap-mean-or-and-95-ci" class="section level3">
<h3>Bootstrap mean OR and 95% CI</h3>
<pre class="r"><code>bootstrap_df|&gt; 
  summarize(
    mean_OR = mean(OR),
    CI_lower = quantile(OR, 0.025),
    CI_upper = quantile(OR, 0.975)
    )|&gt; 
  knitr::kable(digits = 3)</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">mean_OR</th>
<th align="right">CI_lower</th>
<th align="right">CI_upper</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">0.000</td>
<td align="right">0.000</td>
<td align="right">0.000</td>
</tr>
<tr class="even">
<td align="left">age</td>
<td align="right">1.058</td>
<td align="right">1.028</td>
<td align="right">1.090</td>
</tr>
<tr class="odd">
<td align="left">genderMale</td>
<td align="right">6.864</td>
<td align="right">3.494</td>
<td align="right">13.229</td>
</tr>
<tr class="even">
<td align="left">marriageDivorced</td>
<td align="right">3.877</td>
<td align="right">0.979</td>
<td align="right">9.787</td>
</tr>
<tr class="odd">
<td align="left">marriageLiving with partner</td>
<td align="right">3.382</td>
<td align="right">0.928</td>
<td align="right">8.188</td>
</tr>
<tr class="even">
<td align="left">marriageNever married</td>
<td align="right">4.600</td>
<td align="right">1.638</td>
<td align="right">11.053</td>
</tr>
<tr class="odd">
<td align="left">marriageSeparated</td>
<td align="right">4.945</td>
<td align="right">0.835</td>
<td align="right">12.778</td>
</tr>
<tr class="even">
<td align="left">marriageWidowed</td>
<td align="right">11.232</td>
<td align="right">0.000</td>
<td align="right">44.706</td>
</tr>
<tr class="odd">
<td align="left">raceMexican American</td>
<td align="right">1.691</td>
<td align="right">0.504</td>
<td align="right">3.844</td>
</tr>
<tr class="even">
<td align="left">raceNon-Hispanic Black</td>
<td align="right">8.593</td>
<td align="right">4.586</td>
<td align="right">15.826</td>
</tr>
<tr class="odd">
<td align="left">raceOther Hispanic</td>
<td align="right">3.718</td>
<td align="right">1.214</td>
<td align="right">8.720</td>
</tr>
<tr class="even">
<td align="left">raceOther Race - Including Multi-Racial</td>
<td align="right">0.000</td>
<td align="right">0.000</td>
<td align="right">0.000</td>
</tr>
<tr class="odd">
<td align="left">samesexcontact</td>
<td align="right">18.509</td>
<td align="right">10.062</td>
<td align="right">31.310</td>
</tr>
</tbody>
</table>
<p><strong>Bootstrap Confidence Intervals:</strong></p>
<ul>
<li>The bootstrap analysis yields informative insights into the
association between various sociodemographic factors and HIV outcomes.
<ul>
<li>Notably, the wide 95% confidence intervals (CI) for most variables,
excluding age, suggest substantial uncertainty in the estimated odds
ratios. The variable “samesexcontact” stands out with a mean odds ratio
of 18.499 and a relatively narrow CI (10.862 to 31.096), indicating a
robust positive association with HIV risk.</li>
<li>In contrast, variables like “genderMale,” “marriageDivorced,”
“marriageLiving with partner,” “marriageNever married,”
“marriageSeparated,” “marriageWidowed,” “raceMexican American,”
“raceNon-Hispanic Black,” and “raceOther Hispanic” exhibit wide CIs,
signifying considerable variability in their associations with HIV.</li>
</ul></li>
<li>The broad 95% CI underscores the uncertainty in the magnitude of
these associations and suggests a need for caution in drawing definitive
conclusions. This may be attributed to sample variability or other
unaccounted factors influencing the observed relationships.</li>
</ul>
</div>
</div>
<div id="conclusion" class="section level2">
<h2>Conclusion:</h2>
<p>The logistic regression and bootstrap analyses indicate that several
demographic factors are associated with HIV outcomes, same-sex behavior
showing a particularly strong positive association. However, the wide
95% confidence intervals for most variables, excluding age, show
significant uncertainty in the estimated odds ratios, highlighting the
limitations of the study. These broad intervals may stem from sample
variability or unaccounted confounders, necessitating caution in drawing
definitive conclusions.</p>
<p>Therefore, future research should explore larger and more diverse
datasets to enhance the generalizability of findings and address
potential sources of variability. Additionally, a thorough investigation
into the complex interplay between demographic variables and HIV risk,
considering potential interactions and subgroup analyses, could provide
a more nuanced understanding of these associations. Moreover, the study
could benefit from incorporating behavioral and contextual factors that
might contribute to HIV risk.</p>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->
<script>
$(document).ready(function () {
  window.initializeCodeFolding("hide" === "show");
});
</script>


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
