---
title: "P8105: Project Report"
author: "Junjie Hu, Ruixi Li, Xuan Lu, Tianyun Jiang, Qinting Shen"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_float: true
---

```{r defaults, echo = FALSE, message = FALSE, warning = FALSE}
# load necessary packages


# set knitr defaults
knitr::opts_chunk$set(
    echo      = TRUE
  , message   = FALSE
  , fig.align = "center"
)

# set theme defaults
theme_set(
  theme_bw() +
  theme(
    legend.position = "bottom"
    , plot.title    = element_text(hjust = 0.5)
    , plot.subtitle = element_text(hjust = 0.5)    
    , plot.caption  = element_text(hjust = 0.0)
  )
)

# set color scale defaults
options(
    ggplot2.continuous.colour = "viridis"
  , ggplot2.continuous.fill   = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete   = scale_fill_viridis_d
```

## Motivation

Global prevalence among adults (the percent of people ages 15-49 who are infected) has leveled since 2001 and was 0.7% in 2022. There were 39 million people living with HIV in 2022, up from 31.5 million in 2010, the result of continuing new infections and people living longer with HIV. is driven by the ambitious goal set forth by the Centers for Disease Control and Prevention (CDC) to end the HIV epidemic in the United States by 2025. This comprehensive approach is vital in understanding the dynamics of the epidemic, identifying the demographic and socioeconomic factors that contribute to the disease's prevalence, and uncovering actionable insights that could lead to effective intervention strategies. By dissecting the temporal progression of HIV and its incidence across different strata of the population, we aim to pinpoint disparities in transmission rates and healthcare outcomes that may otherwise be obscured in aggregate data. Furthermore, the logistic regression analysis elucidates the complex interplay of risk factors, providing a nuanced risk profile that can inform targeted public health initiatives and resource allocation.



## Related Work

The work is inspired by similar studies that have successfully leveraged statistical analyses to guide public health policies and interventions, such as the multifaceted approach taken in San Francisco, which resulted in a significant decrease in new HIV diagnoses, serving as a model for other cities following the CDC's initiative(https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8546755/). These efforts are crucial stepping stones toward the CDC's goal, representing a concerted effort to leverage data analytics in the battle against HIV and ultimately achieve a significant public health milestone.


## Initial Questions



## Data Sources and Cleaning


### HIV surveillance 


### risk factor investigation


## Exploratory analysis



## Additional analysis



## Discussion & Conclusion


